2023-05-23 06:52:16,780 (1488/MainThread) mssqlcli INFO - Initializing mssqlcli logging.
2023-05-23 06:52:16,786 (1488/MainThread) mssqlcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-05-23 06:52:16,791 (1488/MainThread) mssqlcli.sqltoolsclient INFO - SqlToolsService process id: 1490
2023-05-23 06:52:16,793 (1488/MainThread) mssqlcli.sqltoolsclient INFO - Sql Tools Client Initialized
2023-05-23 06:52:16,793 (1488/MainThread) mssqlcli.mssqlcliclient INFO - Initialized MssqlCliClient with owner Uri mssql-cli-urn:uuid:201abe4d-f415-493d-8e79-6dbeede669a7
2023-05-23 06:52:16,793 (1488/MainThread) mssqlcli.sqltoolsclient INFO - SqlToolsClient connection request Id 234058838231237803103674639578006578044 and owner Uri mssql-cli-urn:uuid:201abe4d-f415-493d-8e79-6dbeede669a7
2023-05-23 06:52:18,176 (1488/Json_Rpc_Response_Thread) mssqlcli.jsonrpc.jsonrpcclient INFO - {'jsonrpc': '2.0', 'id': '234058838231237803103674639578006578044', 'result': True}
2023-05-23 06:52:18,181 (1488/Json_Rpc_Response_Thread) mssqlcli.jsonrpc.jsonrpcclient INFO - {'jsonrpc': '2.0', 'method': 'connection/complete', 'params': {'ownerUri': 'mssql-cli-urn:uuid:201abe4d-f415-493d-8e79-6dbeede669a7', 'connectionId': None, 'messages': 'ServerName cannot be null or empty', 'errorMessage': None, 'errorNumber': 0, 'serverInfo': None, 'connectionSummary': None, 'type': 'Default'}}
2023-05-23 06:52:18,250 (1488/MainThread) mssqlcli.mssqlcliclient ERROR - ServerName cannot be null or empty
2023-05-23 06:52:18,251 (1488/completion_refresh) mssqlcli.sqltoolsclient INFO - SqlToolsClient connection request Id 45425304441784760147482205361108490124 and owner Uri mssql-cli-urn:uuid:348def10-67da-4cfc-950a-bb749e586f92
2023-05-23 06:52:18,268 (1488/Json_Rpc_Response_Thread) mssqlcli.jsonrpc.jsonrpcclient INFO - {'jsonrpc': '2.0', 'id': '45425304441784760147482205361108490124', 'result': True}
2023-05-23 06:52:18,268 (1488/Json_Rpc_Response_Thread) mssqlcli.jsonrpc.jsonrpcclient INFO - {'jsonrpc': '2.0', 'method': 'connection/complete', 'params': {'ownerUri': 'mssql-cli-urn:uuid:348def10-67da-4cfc-950a-bb749e586f92', 'connectionId': None, 'messages': 'ServerName cannot be null or empty', 'errorMessage': None, 'errorNumber': 0, 'serverInfo': None, 'connectionSummary': None, 'type': 'Default'}}
2023-05-23 06:52:18,362 (1488/completion_refresh) mssqlcli.mssqlcliclient ERROR - ServerName cannot be null or empty
2023-05-23 06:52:18,362 (1488/completion_refresh) mssqlcli.completion_refresher ERROR - 
2023-05-23 06:52:22,194 (1488/MainThread) mssqlcli.jsonrpc.jsonrpcclient INFO - Shutting down Json rpc client.
2023-05-23 06:52:22,195 (1488/MainThread) mssqlcli.sqltoolsclient INFO - Shutting down Sql Tools Client Process Id: 1490
2023-05-23 06:52:22,296 (1488/MainThread) mssqlcli.mssqlcliclient INFO - Shutdown MssqlCliClient
2023-05-23 06:52:22,296 (1488/MainThread) mssqlcli.jsonrpc.jsonrpcclient INFO - Shutting down Json rpc client.
2023-05-23 06:52:22,296 (1488/MainThread) mssqlcli.sqltoolsclient INFO - Shutting down Sql Tools Client Process Id: 1490
2023-05-23 06:52:22,396 (1488/MainThread) mssqlcli.mssqlcliclient INFO - Shutdown MssqlCliClient
2023-05-23 06:52:26,721 (1558/MainThread) mssqlcli INFO - Initializing mssqlcli logging.
2023-05-23 06:52:26,723 (1558/MainThread) mssqlcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-05-23 06:52:26,727 (1558/MainThread) mssqlcli.sqltoolsclient INFO - SqlToolsService process id: 1560
2023-05-23 06:52:26,728 (1558/MainThread) mssqlcli.sqltoolsclient INFO - Sql Tools Client Initialized
2023-05-23 06:52:26,728 (1558/MainThread) mssqlcli.mssqlcliclient INFO - Initialized MssqlCliClient with owner Uri mssql-cli-urn:uuid:69f29fc2-ab79-40a6-b5bc-e3a82e6bc34c
2023-05-23 06:52:26,728 (1558/MainThread) mssqlcli.sqltoolsclient INFO - SqlToolsClient connection request Id 5229999528654266605233139661449680971 and owner Uri mssql-cli-urn:uuid:69f29fc2-ab79-40a6-b5bc-e3a82e6bc34c
2023-05-23 06:52:27,491 (1558/Json_Rpc_Response_Thread) mssqlcli.jsonrpc.jsonrpcclient INFO - {'jsonrpc': '2.0', 'id': '5229999528654266605233139661449680971', 'result': True}
2023-05-23 06:52:45,007 (1558/Json_Rpc_Response_Thread) mssqlcli.jsonrpc.jsonrpcclient INFO - {'jsonrpc': '2.0', 'method': 'connection/complete', 'params': {'ownerUri': 'mssql-cli-urn:uuid:69f29fc2-ab79-40a6-b5bc-e3a82e6bc34c', 'connectionId': None, 'messages': 'System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 35 - An internal exception was caught) ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000005, 6): No such device or address\n   at System.Net.Dns.InternalGetHostByName(String hostName)\n   at System.Net.Dns.GetHostAddresses(String hostNameOrAddress)\n   at System.Data.SqlClient.SNI.SNITCPHandle.Connect(String serverName, Int32 port, TimeSpan timeout)\n   at System.Data.SqlClient.SNI.SNITCPHandle..ctor(String serverName, Int32 port, Int64 timerExpire, Object callbackObject, Boolean parallel)\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken)\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\n   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)\n   at System.Data.ProviderBase.DbConnectionFactory.<>c__DisplayClass40_0.<TryGetConnection>b__1(Task`1 _)\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)\n--- End of stack trace from previous location where exception was thrown ---\n   at Microsoft.SqlTools.ServiceLayer.Connection.ReliableConnection.ReliableSqlConnection.<>c__DisplayClass28_0.<<OpenAsync>b__0>d.MoveNext() in D:\\a\\1\\s\\src\\Microsoft.SqlTools.ManagedBatchParser\\ReliableConnection\\ReliableSqlConnection.cs:line 303\n--- End of stack trace from previous location where exception was thrown ---\n   at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.TryOpenConnection(ConnectionInfo connectionInfo, ConnectParams connectionParams) in D:\\a\\1\\s\\src\\Microsoft.SqlTools.ServiceLayer\\Connection\\ConnectionService.cs:line 521\nClientConnectionId:00000000-0000-0000-0000-000000000000', 'errorMessage': 'A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 35 - An internal exception was caught)', 'errorNumber': 0, 'serverInfo': None, 'connectionSummary': None, 'type': 'Default'}}
2023-05-23 06:52:45,043 (1558/MainThread) mssqlcli.mssqlcliclient ERROR - System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 35 - An internal exception was caught) ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000005, 6): No such device or address
   at System.Net.Dns.InternalGetHostByName(String hostName)
   at System.Net.Dns.GetHostAddresses(String hostNameOrAddress)
   at System.Data.SqlClient.SNI.SNITCPHandle.Connect(String serverName, Int32 port, TimeSpan timeout)
   at System.Data.SqlClient.SNI.SNITCPHandle..ctor(String serverName, Int32 port, Int64 timerExpire, Object callbackObject, Boolean parallel)
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.<>c__DisplayClass40_0.<TryGetConnection>b__1(Task`1 _)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.SqlTools.ServiceLayer.Connection.ReliableConnection.ReliableSqlConnection.<>c__DisplayClass28_0.<<OpenAsync>b__0>d.MoveNext() in D:\a\1\s\src\Microsoft.SqlTools.ManagedBatchParser\ReliableConnection\ReliableSqlConnection.cs:line 303
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.TryOpenConnection(ConnectionInfo connectionInfo, ConnectParams connectionParams) in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\Connection\ConnectionService.cs:line 521
ClientConnectionId:00000000-0000-0000-0000-000000000000
2023-05-23 06:52:45,043 (1558/MainThread) mssqlcli.jsonrpc.jsonrpcclient INFO - Shutting down Json rpc client.
2023-05-23 06:52:45,043 (1558/MainThread) mssqlcli.sqltoolsclient INFO - Shutting down Sql Tools Client Process Id: 1560
2023-05-23 06:52:45,144 (1558/MainThread) mssqlcli.mssqlcliclient INFO - Shutdown MssqlCliClient
2023-05-23 06:52:45,146 (1558/MainThread) mssqlcli.jsonrpc.jsonrpcclient INFO - Shutting down Json rpc client.
2023-05-23 06:52:45,146 (1558/MainThread) mssqlcli.sqltoolsclient INFO - Shutting down Sql Tools Client Process Id: 1560
2023-05-23 06:55:20,269 (1663/MainThread) mssqlcli INFO - Initializing mssqlcli logging.
2023-05-23 06:55:20,272 (1663/MainThread) mssqlcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-05-23 06:55:20,276 (1663/MainThread) mssqlcli.sqltoolsclient INFO - SqlToolsService process id: 1665
2023-05-23 06:55:20,277 (1663/MainThread) mssqlcli.sqltoolsclient INFO - Sql Tools Client Initialized
2023-05-23 06:55:20,277 (1663/MainThread) mssqlcli.mssqlcliclient INFO - Initialized MssqlCliClient with owner Uri mssql-cli-urn:uuid:3b53a4a2-8cd6-4334-a1df-9eac2f2e8256
2023-05-23 06:55:20,277 (1663/MainThread) mssqlcli.sqltoolsclient INFO - SqlToolsClient connection request Id 238317824704786357812404635078360279412 and owner Uri mssql-cli-urn:uuid:3b53a4a2-8cd6-4334-a1df-9eac2f2e8256
2023-05-23 06:55:21,190 (1663/Json_Rpc_Response_Thread) mssqlcli.jsonrpc.jsonrpcclient INFO - {'jsonrpc': '2.0', 'id': '238317824704786357812404635078360279412', 'result': True}
2023-05-23 06:55:38,744 (1663/Json_Rpc_Response_Thread) mssqlcli.jsonrpc.jsonrpcclient INFO - {'jsonrpc': '2.0', 'method': 'connection/complete', 'params': {'ownerUri': 'mssql-cli-urn:uuid:3b53a4a2-8cd6-4334-a1df-9eac2f2e8256', 'connectionId': None, 'messages': 'System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 35 - An internal exception was caught) ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000005, 6): No such device or address\n   at System.Net.Dns.InternalGetHostByName(String hostName)\n   at System.Net.Dns.GetHostAddresses(String hostNameOrAddress)\n   at System.Data.SqlClient.SNI.SNITCPHandle.Connect(String serverName, Int32 port, TimeSpan timeout)\n   at System.Data.SqlClient.SNI.SNITCPHandle..ctor(String serverName, Int32 port, Int64 timerExpire, Object callbackObject, Boolean parallel)\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken)\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\n   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)\n   at System.Data.ProviderBase.DbConnectionFactory.<>c__DisplayClass40_0.<TryGetConnection>b__1(Task`1 _)\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)\n--- End of stack trace from previous location where exception was thrown ---\n   at Microsoft.SqlTools.ServiceLayer.Connection.ReliableConnection.ReliableSqlConnection.<>c__DisplayClass28_0.<<OpenAsync>b__0>d.MoveNext() in D:\\a\\1\\s\\src\\Microsoft.SqlTools.ManagedBatchParser\\ReliableConnection\\ReliableSqlConnection.cs:line 303\n--- End of stack trace from previous location where exception was thrown ---\n   at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.TryOpenConnection(ConnectionInfo connectionInfo, ConnectParams connectionParams) in D:\\a\\1\\s\\src\\Microsoft.SqlTools.ServiceLayer\\Connection\\ConnectionService.cs:line 521\nClientConnectionId:00000000-0000-0000-0000-000000000000', 'errorMessage': 'A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 35 - An internal exception was caught)', 'errorNumber': 0, 'serverInfo': None, 'connectionSummary': None, 'type': 'Default'}}
2023-05-23 06:55:38,745 (1663/MainThread) mssqlcli.mssqlcliclient ERROR - System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 35 - An internal exception was caught) ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000005, 6): No such device or address
   at System.Net.Dns.InternalGetHostByName(String hostName)
   at System.Net.Dns.GetHostAddresses(String hostNameOrAddress)
   at System.Data.SqlClient.SNI.SNITCPHandle.Connect(String serverName, Int32 port, TimeSpan timeout)
   at System.Data.SqlClient.SNI.SNITCPHandle..ctor(String serverName, Int32 port, Int64 timerExpire, Object callbackObject, Boolean parallel)
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.<>c__DisplayClass40_0.<TryGetConnection>b__1(Task`1 _)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.SqlTools.ServiceLayer.Connection.ReliableConnection.ReliableSqlConnection.<>c__DisplayClass28_0.<<OpenAsync>b__0>d.MoveNext() in D:\a\1\s\src\Microsoft.SqlTools.ManagedBatchParser\ReliableConnection\ReliableSqlConnection.cs:line 303
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.TryOpenConnection(ConnectionInfo connectionInfo, ConnectParams connectionParams) in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\Connection\ConnectionService.cs:line 521
ClientConnectionId:00000000-0000-0000-0000-000000000000
2023-05-23 06:55:38,746 (1663/MainThread) mssqlcli.jsonrpc.jsonrpcclient INFO - Shutting down Json rpc client.
2023-05-23 06:55:38,746 (1663/MainThread) mssqlcli.sqltoolsclient INFO - Shutting down Sql Tools Client Process Id: 1665
2023-05-23 06:55:38,847 (1663/MainThread) mssqlcli.mssqlcliclient INFO - Shutdown MssqlCliClient
2023-05-23 06:55:38,849 (1663/MainThread) mssqlcli.jsonrpc.jsonrpcclient INFO - Shutting down Json rpc client.
2023-05-23 06:55:38,850 (1663/MainThread) mssqlcli.sqltoolsclient INFO - Shutting down Sql Tools Client Process Id: 1665
2023-05-23 06:57:22,203 (1695/MainThread) mssqlcli INFO - Initializing mssqlcli logging.
2023-05-23 06:57:22,204 (1695/MainThread) mssqlcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-05-23 06:57:22,206 (1695/MainThread) mssqlcli.sqltoolsclient INFO - SqlToolsService process id: 1697
2023-05-23 06:57:22,207 (1695/MainThread) mssqlcli.sqltoolsclient INFO - Sql Tools Client Initialized
2023-05-23 06:57:22,207 (1695/MainThread) mssqlcli.mssqlcliclient INFO - Initialized MssqlCliClient with owner Uri mssql-cli-urn:uuid:c4771bac-9f46-432a-b0cc-c41ec71dcbe4
2023-05-23 06:57:22,207 (1695/MainThread) mssqlcli.sqltoolsclient INFO - SqlToolsClient connection request Id 239378657448943274273817467597877048726 and owner Uri mssql-cli-urn:uuid:c4771bac-9f46-432a-b0cc-c41ec71dcbe4
2023-05-23 06:57:22,608 (1695/Json_Rpc_Response_Thread) mssqlcli.jsonrpc.jsonrpcclient INFO - {'jsonrpc': '2.0', 'id': '239378657448943274273817467597877048726', 'result': True}
2023-05-23 06:57:40,083 (1695/Json_Rpc_Response_Thread) mssqlcli.jsonrpc.jsonrpcclient INFO - {'jsonrpc': '2.0', 'method': 'connection/complete', 'params': {'ownerUri': 'mssql-cli-urn:uuid:c4771bac-9f46-432a-b0cc-c41ec71dcbe4', 'connectionId': None, 'messages': 'System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 35 - An internal exception was caught) ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000005, 6): No such device or address\n   at System.Net.Dns.InternalGetHostByName(String hostName)\n   at System.Net.Dns.GetHostAddresses(String hostNameOrAddress)\n   at System.Data.SqlClient.SNI.SNITCPHandle.Connect(String serverName, Int32 port, TimeSpan timeout)\n   at System.Data.SqlClient.SNI.SNITCPHandle..ctor(String serverName, Int32 port, Int64 timerExpire, Object callbackObject, Boolean parallel)\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken)\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\n   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)\n   at System.Data.ProviderBase.DbConnectionFactory.<>c__DisplayClass40_0.<TryGetConnection>b__1(Task`1 _)\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)\n--- End of stack trace from previous location where exception was thrown ---\n   at Microsoft.SqlTools.ServiceLayer.Connection.ReliableConnection.ReliableSqlConnection.<>c__DisplayClass28_0.<<OpenAsync>b__0>d.MoveNext() in D:\\a\\1\\s\\src\\Microsoft.SqlTools.ManagedBatchParser\\ReliableConnection\\ReliableSqlConnection.cs:line 303\n--- End of stack trace from previous location where exception was thrown ---\n   at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.TryOpenConnection(ConnectionInfo connectionInfo, ConnectParams connectionParams) in D:\\a\\1\\s\\src\\Microsoft.SqlTools.ServiceLayer\\Connection\\ConnectionService.cs:line 521\nClientConnectionId:00000000-0000-0000-0000-000000000000', 'errorMessage': 'A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 35 - An internal exception was caught)', 'errorNumber': 0, 'serverInfo': None, 'connectionSummary': None, 'type': 'Default'}}
2023-05-23 06:57:40,107 (1695/MainThread) mssqlcli.mssqlcliclient ERROR - System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 35 - An internal exception was caught) ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000005, 6): No such device or address
   at System.Net.Dns.InternalGetHostByName(String hostName)
   at System.Net.Dns.GetHostAddresses(String hostNameOrAddress)
   at System.Data.SqlClient.SNI.SNITCPHandle.Connect(String serverName, Int32 port, TimeSpan timeout)
   at System.Data.SqlClient.SNI.SNITCPHandle..ctor(String serverName, Int32 port, Int64 timerExpire, Object callbackObject, Boolean parallel)
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.<>c__DisplayClass40_0.<TryGetConnection>b__1(Task`1 _)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.SqlTools.ServiceLayer.Connection.ReliableConnection.ReliableSqlConnection.<>c__DisplayClass28_0.<<OpenAsync>b__0>d.MoveNext() in D:\a\1\s\src\Microsoft.SqlTools.ManagedBatchParser\ReliableConnection\ReliableSqlConnection.cs:line 303
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.TryOpenConnection(ConnectionInfo connectionInfo, ConnectParams connectionParams) in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\Connection\ConnectionService.cs:line 521
ClientConnectionId:00000000-0000-0000-0000-000000000000
2023-05-23 06:57:40,107 (1695/MainThread) mssqlcli.jsonrpc.jsonrpcclient INFO - Shutting down Json rpc client.
2023-05-23 06:57:40,107 (1695/MainThread) mssqlcli.sqltoolsclient INFO - Shutting down Sql Tools Client Process Id: 1697
2023-05-23 06:57:40,207 (1695/MainThread) mssqlcli.mssqlcliclient INFO - Shutdown MssqlCliClient
2023-05-23 06:57:40,209 (1695/MainThread) mssqlcli.jsonrpc.jsonrpcclient INFO - Shutting down Json rpc client.
2023-05-23 06:57:40,209 (1695/MainThread) mssqlcli.sqltoolsclient INFO - Shutting down Sql Tools Client Process Id: 1697
2023-05-23 06:58:03,133 (1739/MainThread) mssqlcli INFO - Initializing mssqlcli logging.
2023-05-23 06:58:03,136 (1739/MainThread) mssqlcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-05-23 06:58:03,139 (1739/MainThread) mssqlcli.sqltoolsclient INFO - SqlToolsService process id: 1741
2023-05-23 06:58:03,140 (1739/MainThread) mssqlcli.sqltoolsclient INFO - Sql Tools Client Initialized
2023-05-23 06:58:03,140 (1739/MainThread) mssqlcli.mssqlcliclient INFO - Initialized MssqlCliClient with owner Uri mssql-cli-urn:uuid:47317459-e826-439b-8b05-3f6bbaa3c44c
2023-05-23 06:58:03,140 (1739/MainThread) mssqlcli.sqltoolsclient INFO - SqlToolsClient connection request Id 317539902710096290171876415056880748746 and owner Uri mssql-cli-urn:uuid:47317459-e826-439b-8b05-3f6bbaa3c44c
2023-05-23 06:58:03,841 (1739/Json_Rpc_Response_Thread) mssqlcli.jsonrpc.jsonrpcclient INFO - {'jsonrpc': '2.0', 'id': '317539902710096290171876415056880748746', 'result': True}
2023-05-23 06:58:21,337 (1739/Json_Rpc_Response_Thread) mssqlcli.jsonrpc.jsonrpcclient INFO - {'jsonrpc': '2.0', 'method': 'connection/complete', 'params': {'ownerUri': 'mssql-cli-urn:uuid:47317459-e826-439b-8b05-3f6bbaa3c44c', 'connectionId': None, 'messages': 'System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 35 - An internal exception was caught) ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000005, 6): No such device or address\n   at System.Net.Dns.InternalGetHostByName(String hostName)\n   at System.Net.Dns.GetHostAddresses(String hostNameOrAddress)\n   at System.Data.SqlClient.SNI.SNITCPHandle.Connect(String serverName, Int32 port, TimeSpan timeout)\n   at System.Data.SqlClient.SNI.SNITCPHandle..ctor(String serverName, Int32 port, Int64 timerExpire, Object callbackObject, Boolean parallel)\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken)\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\n   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)\n   at System.Data.ProviderBase.DbConnectionFactory.<>c__DisplayClass40_0.<TryGetConnection>b__1(Task`1 _)\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)\n--- End of stack trace from previous location where exception was thrown ---\n   at Microsoft.SqlTools.ServiceLayer.Connection.ReliableConnection.ReliableSqlConnection.<>c__DisplayClass28_0.<<OpenAsync>b__0>d.MoveNext() in D:\\a\\1\\s\\src\\Microsoft.SqlTools.ManagedBatchParser\\ReliableConnection\\ReliableSqlConnection.cs:line 303\n--- End of stack trace from previous location where exception was thrown ---\n   at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.TryOpenConnection(ConnectionInfo connectionInfo, ConnectParams connectionParams) in D:\\a\\1\\s\\src\\Microsoft.SqlTools.ServiceLayer\\Connection\\ConnectionService.cs:line 521\nClientConnectionId:00000000-0000-0000-0000-000000000000', 'errorMessage': 'A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 35 - An internal exception was caught)', 'errorNumber': 0, 'serverInfo': None, 'connectionSummary': None, 'type': 'Default'}}
2023-05-23 06:58:21,343 (1739/MainThread) mssqlcli.mssqlcliclient ERROR - System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 35 - An internal exception was caught) ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000005, 6): No such device or address
   at System.Net.Dns.InternalGetHostByName(String hostName)
   at System.Net.Dns.GetHostAddresses(String hostNameOrAddress)
   at System.Data.SqlClient.SNI.SNITCPHandle.Connect(String serverName, Int32 port, TimeSpan timeout)
   at System.Data.SqlClient.SNI.SNITCPHandle..ctor(String serverName, Int32 port, Int64 timerExpire, Object callbackObject, Boolean parallel)
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.<>c__DisplayClass40_0.<TryGetConnection>b__1(Task`1 _)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.SqlTools.ServiceLayer.Connection.ReliableConnection.ReliableSqlConnection.<>c__DisplayClass28_0.<<OpenAsync>b__0>d.MoveNext() in D:\a\1\s\src\Microsoft.SqlTools.ManagedBatchParser\ReliableConnection\ReliableSqlConnection.cs:line 303
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.TryOpenConnection(ConnectionInfo connectionInfo, ConnectParams connectionParams) in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\Connection\ConnectionService.cs:line 521
ClientConnectionId:00000000-0000-0000-0000-000000000000
2023-05-23 06:58:21,344 (1739/MainThread) mssqlcli.jsonrpc.jsonrpcclient INFO - Shutting down Json rpc client.
2023-05-23 06:58:21,344 (1739/MainThread) mssqlcli.sqltoolsclient INFO - Shutting down Sql Tools Client Process Id: 1741
2023-05-23 06:58:21,444 (1739/MainThread) mssqlcli.mssqlcliclient INFO - Shutdown MssqlCliClient
2023-05-23 06:58:21,446 (1739/MainThread) mssqlcli.jsonrpc.jsonrpcclient INFO - Shutting down Json rpc client.
2023-05-23 06:58:21,446 (1739/MainThread) mssqlcli.sqltoolsclient INFO - Shutting down Sql Tools Client Process Id: 1741
2023-05-23 06:58:29,362 (1788/MainThread) mssqlcli INFO - Initializing mssqlcli logging.
2023-05-23 06:58:29,365 (1788/MainThread) mssqlcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-05-23 06:58:29,368 (1788/MainThread) mssqlcli.sqltoolsclient INFO - SqlToolsService process id: 1790
2023-05-23 06:58:29,370 (1788/MainThread) mssqlcli.sqltoolsclient INFO - Sql Tools Client Initialized
2023-05-23 06:58:29,370 (1788/MainThread) mssqlcli.mssqlcliclient INFO - Initialized MssqlCliClient with owner Uri mssql-cli-urn:uuid:1846c659-65df-4686-9dff-ed6e9a9536b0
2023-05-23 06:58:29,370 (1788/MainThread) mssqlcli.sqltoolsclient INFO - SqlToolsClient connection request Id 85166418361472547105356577934835352662 and owner Uri mssql-cli-urn:uuid:1846c659-65df-4686-9dff-ed6e9a9536b0
2023-05-23 06:58:30,211 (1788/Json_Rpc_Response_Thread) mssqlcli.jsonrpc.jsonrpcclient INFO - {'jsonrpc': '2.0', 'id': '85166418361472547105356577934835352662', 'result': True}
2023-05-23 06:58:45,074 (1788/Json_Rpc_Response_Thread) mssqlcli.jsonrpc.jsonrpcclient INFO - {'jsonrpc': '2.0', 'method': 'connection/complete', 'params': {'ownerUri': 'mssql-cli-urn:uuid:1846c659-65df-4686-9dff-ed6e9a9536b0', 'connectionId': None, 'messages': 'System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 40 - Could not open a connection to SQL Server)\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken)\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\n   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)\n   at System.Data.ProviderBase.DbConnectionFactory.<>c__DisplayClass40_0.<TryGetConnection>b__1(Task`1 _)\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)\n--- End of stack trace from previous location where exception was thrown ---\n   at Microsoft.SqlTools.ServiceLayer.Connection.ReliableConnection.ReliableSqlConnection.<>c__DisplayClass28_0.<<OpenAsync>b__0>d.MoveNext() in D:\\a\\1\\s\\src\\Microsoft.SqlTools.ManagedBatchParser\\ReliableConnection\\ReliableSqlConnection.cs:line 303\n--- End of stack trace from previous location where exception was thrown ---\n   at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.TryOpenConnection(ConnectionInfo connectionInfo, ConnectParams connectionParams) in D:\\a\\1\\s\\src\\Microsoft.SqlTools.ServiceLayer\\Connection\\ConnectionService.cs:line 521\nClientConnectionId:00000000-0000-0000-0000-000000000000', 'errorMessage': 'A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 40 - Could not open a connection to SQL Server)', 'errorNumber': 0, 'serverInfo': None, 'connectionSummary': None, 'type': 'Default'}}
2023-05-23 06:58:45,109 (1788/MainThread) mssqlcli.mssqlcliclient ERROR - System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 40 - Could not open a connection to SQL Server)
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.<>c__DisplayClass40_0.<TryGetConnection>b__1(Task`1 _)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.SqlTools.ServiceLayer.Connection.ReliableConnection.ReliableSqlConnection.<>c__DisplayClass28_0.<<OpenAsync>b__0>d.MoveNext() in D:\a\1\s\src\Microsoft.SqlTools.ManagedBatchParser\ReliableConnection\ReliableSqlConnection.cs:line 303
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.TryOpenConnection(ConnectionInfo connectionInfo, ConnectParams connectionParams) in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\Connection\ConnectionService.cs:line 521
ClientConnectionId:00000000-0000-0000-0000-000000000000
2023-05-23 06:58:45,109 (1788/MainThread) mssqlcli.jsonrpc.jsonrpcclient INFO - Shutting down Json rpc client.
2023-05-23 06:58:45,109 (1788/MainThread) mssqlcli.sqltoolsclient INFO - Shutting down Sql Tools Client Process Id: 1790
2023-05-23 06:58:45,210 (1788/MainThread) mssqlcli.mssqlcliclient INFO - Shutdown MssqlCliClient
2023-05-23 06:58:45,211 (1788/MainThread) mssqlcli.jsonrpc.jsonrpcclient INFO - Shutting down Json rpc client.
2023-05-23 06:58:45,212 (1788/MainThread) mssqlcli.sqltoolsclient INFO - Shutting down Sql Tools Client Process Id: 1790
2023-05-23 07:00:36,768 (1947/MainThread) mssqlcli INFO - Initializing mssqlcli logging.
2023-05-23 07:00:36,769 (1947/MainThread) mssqlcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-05-23 07:00:36,772 (1947/MainThread) mssqlcli.sqltoolsclient INFO - SqlToolsService process id: 1949
2023-05-23 07:00:36,772 (1947/MainThread) mssqlcli.sqltoolsclient INFO - Sql Tools Client Initialized
2023-05-23 07:00:36,772 (1947/MainThread) mssqlcli.mssqlcliclient INFO - Initialized MssqlCliClient with owner Uri mssql-cli-urn:uuid:5e40021b-d33e-4f18-9951-9263c388cc85
2023-05-23 07:00:36,772 (1947/MainThread) mssqlcli.sqltoolsclient INFO - SqlToolsClient connection request Id 68944553330599642064404902375776664169 and owner Uri mssql-cli-urn:uuid:5e40021b-d33e-4f18-9951-9263c388cc85
2023-05-23 07:00:37,176 (1947/Json_Rpc_Response_Thread) mssqlcli.jsonrpc.jsonrpcclient INFO - {'jsonrpc': '2.0', 'id': '68944553330599642064404902375776664169', 'result': True}
2023-05-23 07:00:37,852 (1947/Json_Rpc_Response_Thread) mssqlcli.jsonrpc.jsonrpcclient INFO - {'jsonrpc': '2.0', 'method': 'connection/complete', 'params': {'ownerUri': 'mssql-cli-urn:uuid:5e40021b-d33e-4f18-9951-9263c388cc85', 'connectionId': None, 'messages': "System.Data.SqlClient.SqlException (0x80131904): Cannot authenticate using Kerberos. Ensure Kerberos has been initialized on the client with 'kinit' and a Service Principal Name has been registered for the SQL Server to allow Kerberos authentication.\nErrorCode=InternalError, Exception=Interop+NetSecurityNative+GssApiException: GSSAPI operation failed with error - An invalid status code was supplied (SPNEGO cannot find mechanisms to negotiate).\n   at System.Net.Security.NegotiateStreamPal.GssInitSecurityContext(SafeGssContextHandle& context, SafeGssCredHandle credential, Boolean isNtlm, SafeGssNameHandle targetName, GssFlags inFlags, Byte[] buffer, Byte[]& outputBuffer, UInt32& outFlags, Int32& isNtlmUsed)\n   at System.Net.Security.NegotiateStreamPal.EstablishSecurityContext(SafeFreeNegoCredentials credential, SafeDeleteContext& context, String targetName, ContextFlagsPal inFlags, SecurityBuffer inputBuffer, SecurityBuffer outputBuffer, ContextFlagsPal& outFlags)\n   at System.Data.SqlClient.SNI.SNIProxy.GenSspiClientContext(SspiClientContextStatus sspiClientContextStatus, Byte[] receivedBuff, Byte[]& sendBuff, Byte[] serverName)\n   at System.Data.SqlClient.SNI.TdsParserStateObjectManaged.GenerateSspiClientContext(Byte[] receivedBuff, UInt32 receivedLength, Byte[]& sendBuff, UInt32& sendLength, Byte[] _sniSpnBuffer)\n   at System.Data.SqlClient.TdsParser.SNISSPIData(Byte[] receivedBuff, UInt32 receivedLength, Byte[]& sendBuff, UInt32& sendLength)\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken)\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\n   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)\n   at System.Data.ProviderBase.DbConnectionFactory.<>c__DisplayClass40_0.<TryGetConnection>b__1(Task`1 _)\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)\n--- End of stack trace from previous location where exception was thrown ---\n   at Microsoft.SqlTools.ServiceLayer.Connection.ReliableConnection.ReliableSqlConnection.<>c__DisplayClass28_0.<<OpenAsync>b__0>d.MoveNext() in D:\\a\\1\\s\\src\\Microsoft.SqlTools.ManagedBatchParser\\ReliableConnection\\ReliableSqlConnection.cs:line 303\n--- End of stack trace from previous location where exception was thrown ---\n   at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.TryOpenConnection(ConnectionInfo connectionInfo, ConnectParams connectionParams) in D:\\a\\1\\s\\src\\Microsoft.SqlTools.ServiceLayer\\Connection\\ConnectionService.cs:line 521\nClientConnectionId:14238434-702a-4a32-b21a-5b1e475a0a3b", 'errorMessage': "Cannot authenticate using Kerberos. Ensure Kerberos has been initialized on the client with 'kinit' and a Service Principal Name has been registered for the SQL Server to allow Kerberos authentication.\nErrorCode=InternalError, Exception=Interop+NetSecurityNative+GssApiException: GSSAPI operation failed with error - An invalid status code was supplied (SPNEGO cannot find mechanisms to negotiate).\n   at System.Net.Security.NegotiateStreamPal.GssInitSecurityContext(SafeGssContextHandle& context, SafeGssCredHandle credential, Boolean isNtlm, SafeGssNameHandle targetName, GssFlags inFlags, Byte[] buffer, Byte[]& outputBuffer, UInt32& outFlags, Int32& isNtlmUsed)\n   at System.Net.Security.NegotiateStreamPal.EstablishSecurityContext(SafeFreeNegoCredentials credential, SafeDeleteContext& context, String targetName, ContextFlagsPal inFlags, SecurityBuffer inputBuffer, SecurityBuffer outputBuffer, ContextFlagsPal& outFlags)\n   at System.Data.SqlClient.SNI.SNIProxy.GenSspiClientContext(SspiClientContextStatus sspiClientContextStatus, Byte[] receivedBuff, Byte[]& sendBuff, Byte[] serverName)\n   at System.Data.SqlClient.SNI.TdsParserStateObjectManaged.GenerateSspiClientContext(Byte[] receivedBuff, UInt32 receivedLength, Byte[]& sendBuff, UInt32& sendLength, Byte[] _sniSpnBuffer)\n   at System.Data.SqlClient.TdsParser.SNISSPIData(Byte[] receivedBuff, UInt32 receivedLength, Byte[]& sendBuff, UInt32& sendLength)", 'errorNumber': 0, 'serverInfo': None, 'connectionSummary': None, 'type': 'Default'}}
2023-05-23 07:00:37,878 (1947/MainThread) mssqlcli.mssqlcliclient ERROR - System.Data.SqlClient.SqlException (0x80131904): Cannot authenticate using Kerberos. Ensure Kerberos has been initialized on the client with 'kinit' and a Service Principal Name has been registered for the SQL Server to allow Kerberos authentication.
ErrorCode=InternalError, Exception=Interop+NetSecurityNative+GssApiException: GSSAPI operation failed with error - An invalid status code was supplied (SPNEGO cannot find mechanisms to negotiate).
   at System.Net.Security.NegotiateStreamPal.GssInitSecurityContext(SafeGssContextHandle& context, SafeGssCredHandle credential, Boolean isNtlm, SafeGssNameHandle targetName, GssFlags inFlags, Byte[] buffer, Byte[]& outputBuffer, UInt32& outFlags, Int32& isNtlmUsed)
   at System.Net.Security.NegotiateStreamPal.EstablishSecurityContext(SafeFreeNegoCredentials credential, SafeDeleteContext& context, String targetName, ContextFlagsPal inFlags, SecurityBuffer inputBuffer, SecurityBuffer outputBuffer, ContextFlagsPal& outFlags)
   at System.Data.SqlClient.SNI.SNIProxy.GenSspiClientContext(SspiClientContextStatus sspiClientContextStatus, Byte[] receivedBuff, Byte[]& sendBuff, Byte[] serverName)
   at System.Data.SqlClient.SNI.TdsParserStateObjectManaged.GenerateSspiClientContext(Byte[] receivedBuff, UInt32 receivedLength, Byte[]& sendBuff, UInt32& sendLength, Byte[] _sniSpnBuffer)
   at System.Data.SqlClient.TdsParser.SNISSPIData(Byte[] receivedBuff, UInt32 receivedLength, Byte[]& sendBuff, UInt32& sendLength)
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.<>c__DisplayClass40_0.<TryGetConnection>b__1(Task`1 _)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.SqlTools.ServiceLayer.Connection.ReliableConnection.ReliableSqlConnection.<>c__DisplayClass28_0.<<OpenAsync>b__0>d.MoveNext() in D:\a\1\s\src\Microsoft.SqlTools.ManagedBatchParser\ReliableConnection\ReliableSqlConnection.cs:line 303
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.TryOpenConnection(ConnectionInfo connectionInfo, ConnectParams connectionParams) in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\Connection\ConnectionService.cs:line 521
ClientConnectionId:14238434-702a-4a32-b21a-5b1e475a0a3b
2023-05-23 07:00:37,879 (1947/MainThread) mssqlcli.jsonrpc.jsonrpcclient INFO - Shutting down Json rpc client.
2023-05-23 07:00:37,879 (1947/MainThread) mssqlcli.sqltoolsclient INFO - Shutting down Sql Tools Client Process Id: 1949
2023-05-23 07:00:37,979 (1947/MainThread) mssqlcli.mssqlcliclient INFO - Shutdown MssqlCliClient
2023-05-23 07:00:37,981 (1947/MainThread) mssqlcli.jsonrpc.jsonrpcclient INFO - Shutting down Json rpc client.
2023-05-23 07:00:37,981 (1947/MainThread) mssqlcli.sqltoolsclient INFO - Shutting down Sql Tools Client Process Id: 1949
2023-05-23 07:01:02,904 (1996/MainThread) mssqlcli INFO - Initializing mssqlcli logging.
2023-05-23 07:01:02,905 (1996/MainThread) mssqlcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-05-23 07:01:02,907 (1996/MainThread) mssqlcli.sqltoolsclient INFO - SqlToolsService process id: 1998
2023-05-23 07:01:02,908 (1996/MainThread) mssqlcli.sqltoolsclient INFO - Sql Tools Client Initialized
2023-05-23 07:01:02,908 (1996/MainThread) mssqlcli.mssqlcliclient INFO - Initialized MssqlCliClient with owner Uri mssql-cli-urn:uuid:5be557f9-83d6-4e44-81ca-bb9c30c65c94
2023-05-23 07:01:02,908 (1996/MainThread) mssqlcli.sqltoolsclient INFO - SqlToolsClient connection request Id 265603033886503196152154294133659949375 and owner Uri mssql-cli-urn:uuid:5be557f9-83d6-4e44-81ca-bb9c30c65c94
2023-05-23 07:01:03,348 (1996/Json_Rpc_Response_Thread) mssqlcli.jsonrpc.jsonrpcclient INFO - {'jsonrpc': '2.0', 'id': '265603033886503196152154294133659949375', 'result': True}
2023-05-23 07:01:03,865 (1996/Json_Rpc_Response_Thread) mssqlcli.jsonrpc.jsonrpcclient INFO - {'jsonrpc': '2.0', 'method': 'connection/complete', 'params': {'ownerUri': 'mssql-cli-urn:uuid:5be557f9-83d6-4e44-81ca-bb9c30c65c94', 'connectionId': None, 'messages': "System.Data.SqlClient.SqlException (0x80131904): Cannot authenticate using Kerberos. Ensure Kerberos has been initialized on the client with 'kinit' and a Service Principal Name has been registered for the SQL Server to allow Kerberos authentication.\nErrorCode=InternalError, Exception=Interop+NetSecurityNative+GssApiException: GSSAPI operation failed with error - An invalid status code was supplied (SPNEGO cannot find mechanisms to negotiate).\n   at System.Net.Security.NegotiateStreamPal.GssInitSecurityContext(SafeGssContextHandle& context, SafeGssCredHandle credential, Boolean isNtlm, SafeGssNameHandle targetName, GssFlags inFlags, Byte[] buffer, Byte[]& outputBuffer, UInt32& outFlags, Int32& isNtlmUsed)\n   at System.Net.Security.NegotiateStreamPal.EstablishSecurityContext(SafeFreeNegoCredentials credential, SafeDeleteContext& context, String targetName, ContextFlagsPal inFlags, SecurityBuffer inputBuffer, SecurityBuffer outputBuffer, ContextFlagsPal& outFlags)\n   at System.Data.SqlClient.SNI.SNIProxy.GenSspiClientContext(SspiClientContextStatus sspiClientContextStatus, Byte[] receivedBuff, Byte[]& sendBuff, Byte[] serverName)\n   at System.Data.SqlClient.SNI.TdsParserStateObjectManaged.GenerateSspiClientContext(Byte[] receivedBuff, UInt32 receivedLength, Byte[]& sendBuff, UInt32& sendLength, Byte[] _sniSpnBuffer)\n   at System.Data.SqlClient.TdsParser.SNISSPIData(Byte[] receivedBuff, UInt32 receivedLength, Byte[]& sendBuff, UInt32& sendLength)\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken)\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\n   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)\n   at System.Data.ProviderBase.DbConnectionFactory.<>c__DisplayClass40_0.<TryGetConnection>b__1(Task`1 _)\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)\n--- End of stack trace from previous location where exception was thrown ---\n   at Microsoft.SqlTools.ServiceLayer.Connection.ReliableConnection.ReliableSqlConnection.<>c__DisplayClass28_0.<<OpenAsync>b__0>d.MoveNext() in D:\\a\\1\\s\\src\\Microsoft.SqlTools.ManagedBatchParser\\ReliableConnection\\ReliableSqlConnection.cs:line 303\n--- End of stack trace from previous location where exception was thrown ---\n   at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.TryOpenConnection(ConnectionInfo connectionInfo, ConnectParams connectionParams) in D:\\a\\1\\s\\src\\Microsoft.SqlTools.ServiceLayer\\Connection\\ConnectionService.cs:line 521\nClientConnectionId:e6b39378-8a73-465a-871e-cafef1cabc3e", 'errorMessage': "Cannot authenticate using Kerberos. Ensure Kerberos has been initialized on the client with 'kinit' and a Service Principal Name has been registered for the SQL Server to allow Kerberos authentication.\nErrorCode=InternalError, Exception=Interop+NetSecurityNative+GssApiException: GSSAPI operation failed with error - An invalid status code was supplied (SPNEGO cannot find mechanisms to negotiate).\n   at System.Net.Security.NegotiateStreamPal.GssInitSecurityContext(SafeGssContextHandle& context, SafeGssCredHandle credential, Boolean isNtlm, SafeGssNameHandle targetName, GssFlags inFlags, Byte[] buffer, Byte[]& outputBuffer, UInt32& outFlags, Int32& isNtlmUsed)\n   at System.Net.Security.NegotiateStreamPal.EstablishSecurityContext(SafeFreeNegoCredentials credential, SafeDeleteContext& context, String targetName, ContextFlagsPal inFlags, SecurityBuffer inputBuffer, SecurityBuffer outputBuffer, ContextFlagsPal& outFlags)\n   at System.Data.SqlClient.SNI.SNIProxy.GenSspiClientContext(SspiClientContextStatus sspiClientContextStatus, Byte[] receivedBuff, Byte[]& sendBuff, Byte[] serverName)\n   at System.Data.SqlClient.SNI.TdsParserStateObjectManaged.GenerateSspiClientContext(Byte[] receivedBuff, UInt32 receivedLength, Byte[]& sendBuff, UInt32& sendLength, Byte[] _sniSpnBuffer)\n   at System.Data.SqlClient.TdsParser.SNISSPIData(Byte[] receivedBuff, UInt32 receivedLength, Byte[]& sendBuff, UInt32& sendLength)", 'errorNumber': 0, 'serverInfo': None, 'connectionSummary': None, 'type': 'Default'}}
2023-05-23 07:01:03,913 (1996/MainThread) mssqlcli.mssqlcliclient ERROR - System.Data.SqlClient.SqlException (0x80131904): Cannot authenticate using Kerberos. Ensure Kerberos has been initialized on the client with 'kinit' and a Service Principal Name has been registered for the SQL Server to allow Kerberos authentication.
ErrorCode=InternalError, Exception=Interop+NetSecurityNative+GssApiException: GSSAPI operation failed with error - An invalid status code was supplied (SPNEGO cannot find mechanisms to negotiate).
   at System.Net.Security.NegotiateStreamPal.GssInitSecurityContext(SafeGssContextHandle& context, SafeGssCredHandle credential, Boolean isNtlm, SafeGssNameHandle targetName, GssFlags inFlags, Byte[] buffer, Byte[]& outputBuffer, UInt32& outFlags, Int32& isNtlmUsed)
   at System.Net.Security.NegotiateStreamPal.EstablishSecurityContext(SafeFreeNegoCredentials credential, SafeDeleteContext& context, String targetName, ContextFlagsPal inFlags, SecurityBuffer inputBuffer, SecurityBuffer outputBuffer, ContextFlagsPal& outFlags)
   at System.Data.SqlClient.SNI.SNIProxy.GenSspiClientContext(SspiClientContextStatus sspiClientContextStatus, Byte[] receivedBuff, Byte[]& sendBuff, Byte[] serverName)
   at System.Data.SqlClient.SNI.TdsParserStateObjectManaged.GenerateSspiClientContext(Byte[] receivedBuff, UInt32 receivedLength, Byte[]& sendBuff, UInt32& sendLength, Byte[] _sniSpnBuffer)
   at System.Data.SqlClient.TdsParser.SNISSPIData(Byte[] receivedBuff, UInt32 receivedLength, Byte[]& sendBuff, UInt32& sendLength)
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.<>c__DisplayClass40_0.<TryGetConnection>b__1(Task`1 _)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.SqlTools.ServiceLayer.Connection.ReliableConnection.ReliableSqlConnection.<>c__DisplayClass28_0.<<OpenAsync>b__0>d.MoveNext() in D:\a\1\s\src\Microsoft.SqlTools.ManagedBatchParser\ReliableConnection\ReliableSqlConnection.cs:line 303
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.TryOpenConnection(ConnectionInfo connectionInfo, ConnectParams connectionParams) in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\Connection\ConnectionService.cs:line 521
ClientConnectionId:e6b39378-8a73-465a-871e-cafef1cabc3e
2023-05-23 07:01:03,914 (1996/MainThread) mssqlcli.jsonrpc.jsonrpcclient INFO - Shutting down Json rpc client.
2023-05-23 07:01:03,914 (1996/MainThread) mssqlcli.sqltoolsclient INFO - Shutting down Sql Tools Client Process Id: 1998
2023-05-23 07:01:04,014 (1996/MainThread) mssqlcli.mssqlcliclient INFO - Shutdown MssqlCliClient
2023-05-23 07:01:04,016 (1996/MainThread) mssqlcli.jsonrpc.jsonrpcclient INFO - Shutting down Json rpc client.
2023-05-23 07:01:04,016 (1996/MainThread) mssqlcli.sqltoolsclient INFO - Shutting down Sql Tools Client Process Id: 1998
2023-05-23 07:09:15,168 (2937/MainThread) mssqlcli INFO - Initializing mssqlcli logging.
2023-05-23 07:09:15,170 (2937/MainThread) mssqlcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-05-23 07:09:15,171 (2937/MainThread) mssqlcli.sqltoolsclient INFO - SqlToolsService process id: 2939
2023-05-23 07:09:15,172 (2937/MainThread) mssqlcli.sqltoolsclient INFO - Sql Tools Client Initialized
2023-05-23 07:09:15,172 (2937/MainThread) mssqlcli.mssqlcliclient INFO - Initialized MssqlCliClient with owner Uri mssql-cli-urn:uuid:76dd5775-24d2-4a8c-a1c1-d6a5969cbc8f
2023-05-23 07:09:15,172 (2937/MainThread) mssqlcli.sqltoolsclient INFO - SqlToolsClient connection request Id 259971961538628978238169165036584787252 and owner Uri mssql-cli-urn:uuid:76dd5775-24d2-4a8c-a1c1-d6a5969cbc8f
2023-05-23 07:09:15,600 (2937/Json_Rpc_Response_Thread) mssqlcli.jsonrpc.jsonrpcclient INFO - {'jsonrpc': '2.0', 'id': '259971961538628978238169165036584787252', 'result': True}
2023-05-23 07:09:16,149 (2937/Json_Rpc_Response_Thread) mssqlcli.jsonrpc.jsonrpcclient INFO - {'jsonrpc': '2.0', 'method': 'connection/complete', 'params': {'ownerUri': 'mssql-cli-urn:uuid:76dd5775-24d2-4a8c-a1c1-d6a5969cbc8f', 'connectionId': None, 'messages': "System.Data.SqlClient.SqlException (0x80131904): Cannot authenticate using Kerberos. Ensure Kerberos has been initialized on the client with 'kinit' and a Service Principal Name has been registered for the SQL Server to allow Kerberos authentication.\nErrorCode=InternalError, Exception=Interop+NetSecurityNative+GssApiException: GSSAPI operation failed with error - An invalid status code was supplied (SPNEGO cannot find mechanisms to negotiate).\n   at System.Net.Security.NegotiateStreamPal.GssInitSecurityContext(SafeGssContextHandle& context, SafeGssCredHandle credential, Boolean isNtlm, SafeGssNameHandle targetName, GssFlags inFlags, Byte[] buffer, Byte[]& outputBuffer, UInt32& outFlags, Int32& isNtlmUsed)\n   at System.Net.Security.NegotiateStreamPal.EstablishSecurityContext(SafeFreeNegoCredentials credential, SafeDeleteContext& context, String targetName, ContextFlagsPal inFlags, SecurityBuffer inputBuffer, SecurityBuffer outputBuffer, ContextFlagsPal& outFlags)\n   at System.Data.SqlClient.SNI.SNIProxy.GenSspiClientContext(SspiClientContextStatus sspiClientContextStatus, Byte[] receivedBuff, Byte[]& sendBuff, Byte[] serverName)\n   at System.Data.SqlClient.SNI.TdsParserStateObjectManaged.GenerateSspiClientContext(Byte[] receivedBuff, UInt32 receivedLength, Byte[]& sendBuff, UInt32& sendLength, Byte[] _sniSpnBuffer)\n   at System.Data.SqlClient.TdsParser.SNISSPIData(Byte[] receivedBuff, UInt32 receivedLength, Byte[]& sendBuff, UInt32& sendLength)\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken)\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\n   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)\n   at System.Data.ProviderBase.DbConnectionFactory.<>c__DisplayClass40_0.<TryGetConnection>b__1(Task`1 _)\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)\n--- End of stack trace from previous location where exception was thrown ---\n   at Microsoft.SqlTools.ServiceLayer.Connection.ReliableConnection.ReliableSqlConnection.<>c__DisplayClass28_0.<<OpenAsync>b__0>d.MoveNext() in D:\\a\\1\\s\\src\\Microsoft.SqlTools.ManagedBatchParser\\ReliableConnection\\ReliableSqlConnection.cs:line 303\n--- End of stack trace from previous location where exception was thrown ---\n   at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.TryOpenConnection(ConnectionInfo connectionInfo, ConnectParams connectionParams) in D:\\a\\1\\s\\src\\Microsoft.SqlTools.ServiceLayer\\Connection\\ConnectionService.cs:line 521\nClientConnectionId:70cbb3e9-8617-4b06-b969-6e2c7d4a9201", 'errorMessage': "Cannot authenticate using Kerberos. Ensure Kerberos has been initialized on the client with 'kinit' and a Service Principal Name has been registered for the SQL Server to allow Kerberos authentication.\nErrorCode=InternalError, Exception=Interop+NetSecurityNative+GssApiException: GSSAPI operation failed with error - An invalid status code was supplied (SPNEGO cannot find mechanisms to negotiate).\n   at System.Net.Security.NegotiateStreamPal.GssInitSecurityContext(SafeGssContextHandle& context, SafeGssCredHandle credential, Boolean isNtlm, SafeGssNameHandle targetName, GssFlags inFlags, Byte[] buffer, Byte[]& outputBuffer, UInt32& outFlags, Int32& isNtlmUsed)\n   at System.Net.Security.NegotiateStreamPal.EstablishSecurityContext(SafeFreeNegoCredentials credential, SafeDeleteContext& context, String targetName, ContextFlagsPal inFlags, SecurityBuffer inputBuffer, SecurityBuffer outputBuffer, ContextFlagsPal& outFlags)\n   at System.Data.SqlClient.SNI.SNIProxy.GenSspiClientContext(SspiClientContextStatus sspiClientContextStatus, Byte[] receivedBuff, Byte[]& sendBuff, Byte[] serverName)\n   at System.Data.SqlClient.SNI.TdsParserStateObjectManaged.GenerateSspiClientContext(Byte[] receivedBuff, UInt32 receivedLength, Byte[]& sendBuff, UInt32& sendLength, Byte[] _sniSpnBuffer)\n   at System.Data.SqlClient.TdsParser.SNISSPIData(Byte[] receivedBuff, UInt32 receivedLength, Byte[]& sendBuff, UInt32& sendLength)", 'errorNumber': 0, 'serverInfo': None, 'connectionSummary': None, 'type': 'Default'}}
2023-05-23 07:09:16,177 (2937/MainThread) mssqlcli.mssqlcliclient ERROR - System.Data.SqlClient.SqlException (0x80131904): Cannot authenticate using Kerberos. Ensure Kerberos has been initialized on the client with 'kinit' and a Service Principal Name has been registered for the SQL Server to allow Kerberos authentication.
ErrorCode=InternalError, Exception=Interop+NetSecurityNative+GssApiException: GSSAPI operation failed with error - An invalid status code was supplied (SPNEGO cannot find mechanisms to negotiate).
   at System.Net.Security.NegotiateStreamPal.GssInitSecurityContext(SafeGssContextHandle& context, SafeGssCredHandle credential, Boolean isNtlm, SafeGssNameHandle targetName, GssFlags inFlags, Byte[] buffer, Byte[]& outputBuffer, UInt32& outFlags, Int32& isNtlmUsed)
   at System.Net.Security.NegotiateStreamPal.EstablishSecurityContext(SafeFreeNegoCredentials credential, SafeDeleteContext& context, String targetName, ContextFlagsPal inFlags, SecurityBuffer inputBuffer, SecurityBuffer outputBuffer, ContextFlagsPal& outFlags)
   at System.Data.SqlClient.SNI.SNIProxy.GenSspiClientContext(SspiClientContextStatus sspiClientContextStatus, Byte[] receivedBuff, Byte[]& sendBuff, Byte[] serverName)
   at System.Data.SqlClient.SNI.TdsParserStateObjectManaged.GenerateSspiClientContext(Byte[] receivedBuff, UInt32 receivedLength, Byte[]& sendBuff, UInt32& sendLength, Byte[] _sniSpnBuffer)
   at System.Data.SqlClient.TdsParser.SNISSPIData(Byte[] receivedBuff, UInt32 receivedLength, Byte[]& sendBuff, UInt32& sendLength)
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.<>c__DisplayClass40_0.<TryGetConnection>b__1(Task`1 _)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.SqlTools.ServiceLayer.Connection.ReliableConnection.ReliableSqlConnection.<>c__DisplayClass28_0.<<OpenAsync>b__0>d.MoveNext() in D:\a\1\s\src\Microsoft.SqlTools.ManagedBatchParser\ReliableConnection\ReliableSqlConnection.cs:line 303
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.TryOpenConnection(ConnectionInfo connectionInfo, ConnectParams connectionParams) in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\Connection\ConnectionService.cs:line 521
ClientConnectionId:70cbb3e9-8617-4b06-b969-6e2c7d4a9201
2023-05-23 07:09:16,177 (2937/MainThread) mssqlcli.jsonrpc.jsonrpcclient INFO - Shutting down Json rpc client.
2023-05-23 07:09:16,177 (2937/MainThread) mssqlcli.sqltoolsclient INFO - Shutting down Sql Tools Client Process Id: 2939
2023-05-23 07:09:16,278 (2937/MainThread) mssqlcli.mssqlcliclient INFO - Shutdown MssqlCliClient
2023-05-23 07:09:16,279 (2937/MainThread) mssqlcli.jsonrpc.jsonrpcclient INFO - Shutting down Json rpc client.
2023-05-23 07:09:16,279 (2937/MainThread) mssqlcli.sqltoolsclient INFO - Shutting down Sql Tools Client Process Id: 2939
2023-05-23 07:10:28,589 (2978/MainThread) mssqlcli INFO - Initializing mssqlcli logging.
2023-05-23 07:10:28,591 (2978/MainThread) mssqlcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-05-23 07:10:28,592 (2978/MainThread) mssqlcli.sqltoolsclient INFO - SqlToolsService process id: 2980
2023-05-23 07:10:28,593 (2978/MainThread) mssqlcli.sqltoolsclient INFO - Sql Tools Client Initialized
2023-05-23 07:10:28,593 (2978/MainThread) mssqlcli.mssqlcliclient INFO - Initialized MssqlCliClient with owner Uri mssql-cli-urn:uuid:5d5cca71-1bdf-4ae8-9fc8-bd6bfb1b6bea
2023-05-23 07:10:28,593 (2978/MainThread) mssqlcli.sqltoolsclient INFO - SqlToolsClient connection request Id 155651383827557299438576547222733728835 and owner Uri mssql-cli-urn:uuid:5d5cca71-1bdf-4ae8-9fc8-bd6bfb1b6bea
2023-05-23 07:10:29,067 (2978/Json_Rpc_Response_Thread) mssqlcli.jsonrpc.jsonrpcclient INFO - {'jsonrpc': '2.0', 'id': '155651383827557299438576547222733728835', 'result': True}
2023-05-23 07:10:43,944 (2978/Json_Rpc_Response_Thread) mssqlcli.jsonrpc.jsonrpcclient INFO - {'jsonrpc': '2.0', 'method': 'connection/complete', 'params': {'ownerUri': 'mssql-cli-urn:uuid:5d5cca71-1bdf-4ae8-9fc8-bd6bfb1b6bea', 'connectionId': None, 'messages': 'System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 40 - Could not open a connection to SQL Server)\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken)\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\n   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)\n   at System.Data.ProviderBase.DbConnectionFactory.<>c__DisplayClass40_0.<TryGetConnection>b__1(Task`1 _)\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)\n--- End of stack trace from previous location where exception was thrown ---\n   at Microsoft.SqlTools.ServiceLayer.Connection.ReliableConnection.ReliableSqlConnection.<>c__DisplayClass28_0.<<OpenAsync>b__0>d.MoveNext() in D:\\a\\1\\s\\src\\Microsoft.SqlTools.ManagedBatchParser\\ReliableConnection\\ReliableSqlConnection.cs:line 303\n--- End of stack trace from previous location where exception was thrown ---\n   at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.TryOpenConnection(ConnectionInfo connectionInfo, ConnectParams connectionParams) in D:\\a\\1\\s\\src\\Microsoft.SqlTools.ServiceLayer\\Connection\\ConnectionService.cs:line 521\nClientConnectionId:00000000-0000-0000-0000-000000000000', 'errorMessage': 'A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 40 - Could not open a connection to SQL Server)', 'errorNumber': 0, 'serverInfo': None, 'connectionSummary': None, 'type': 'Default'}}
2023-05-23 07:10:43,985 (2978/MainThread) mssqlcli.mssqlcliclient ERROR - System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 40 - Could not open a connection to SQL Server)
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.<>c__DisplayClass40_0.<TryGetConnection>b__1(Task`1 _)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.SqlTools.ServiceLayer.Connection.ReliableConnection.ReliableSqlConnection.<>c__DisplayClass28_0.<<OpenAsync>b__0>d.MoveNext() in D:\a\1\s\src\Microsoft.SqlTools.ManagedBatchParser\ReliableConnection\ReliableSqlConnection.cs:line 303
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.TryOpenConnection(ConnectionInfo connectionInfo, ConnectParams connectionParams) in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\Connection\ConnectionService.cs:line 521
ClientConnectionId:00000000-0000-0000-0000-000000000000
2023-05-23 07:10:43,985 (2978/MainThread) mssqlcli.jsonrpc.jsonrpcclient INFO - Shutting down Json rpc client.
2023-05-23 07:10:43,985 (2978/MainThread) mssqlcli.sqltoolsclient INFO - Shutting down Sql Tools Client Process Id: 2980
2023-05-23 07:10:44,086 (2978/MainThread) mssqlcli.mssqlcliclient INFO - Shutdown MssqlCliClient
2023-05-23 07:10:44,088 (2978/MainThread) mssqlcli.jsonrpc.jsonrpcclient INFO - Shutting down Json rpc client.
2023-05-23 07:10:44,088 (2978/MainThread) mssqlcli.sqltoolsclient INFO - Shutting down Sql Tools Client Process Id: 2980
2023-05-23 07:10:50,909 (3010/MainThread) mssqlcli INFO - Initializing mssqlcli logging.
2023-05-23 07:10:50,911 (3010/MainThread) mssqlcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-05-23 07:10:50,914 (3010/MainThread) mssqlcli.sqltoolsclient INFO - SqlToolsService process id: 3012
2023-05-23 07:10:50,915 (3010/MainThread) mssqlcli.sqltoolsclient INFO - Sql Tools Client Initialized
2023-05-23 07:10:50,915 (3010/MainThread) mssqlcli.mssqlcliclient INFO - Initialized MssqlCliClient with owner Uri mssql-cli-urn:uuid:4dc9c5ea-4ba1-4b2a-83f0-edd98b8645ab
2023-05-23 07:10:50,915 (3010/MainThread) mssqlcli.sqltoolsclient INFO - SqlToolsClient connection request Id 269953561954688876078565538569796324887 and owner Uri mssql-cli-urn:uuid:4dc9c5ea-4ba1-4b2a-83f0-edd98b8645ab
2023-05-23 07:10:51,503 (3010/Json_Rpc_Response_Thread) mssqlcli.jsonrpc.jsonrpcclient INFO - {'jsonrpc': '2.0', 'id': '269953561954688876078565538569796324887', 'result': True}
2023-05-23 07:11:06,142 (3010/Json_Rpc_Response_Thread) mssqlcli.jsonrpc.jsonrpcclient INFO - {'jsonrpc': '2.0', 'method': 'connection/complete', 'params': {'ownerUri': 'mssql-cli-urn:uuid:4dc9c5ea-4ba1-4b2a-83f0-edd98b8645ab', 'connectionId': None, 'messages': 'System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 25 - Connection string is not valid)\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken)\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\n   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)\n   at System.Data.ProviderBase.DbConnectionFactory.<>c__DisplayClass40_0.<TryGetConnection>b__1(Task`1 _)\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)\n--- End of stack trace from previous location where exception was thrown ---\n   at Microsoft.SqlTools.ServiceLayer.Connection.ReliableConnection.ReliableSqlConnection.<>c__DisplayClass28_0.<<OpenAsync>b__0>d.MoveNext() in D:\\a\\1\\s\\src\\Microsoft.SqlTools.ManagedBatchParser\\ReliableConnection\\ReliableSqlConnection.cs:line 303\n--- End of stack trace from previous location where exception was thrown ---\n   at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.TryOpenConnection(ConnectionInfo connectionInfo, ConnectParams connectionParams) in D:\\a\\1\\s\\src\\Microsoft.SqlTools.ServiceLayer\\Connection\\ConnectionService.cs:line 521\nClientConnectionId:00000000-0000-0000-0000-000000000000', 'errorMessage': 'A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 25 - Connection string is not valid)', 'errorNumber': 0, 'serverInfo': None, 'connectionSummary': None, 'type': 'Default'}}
2023-05-23 07:11:06,160 (3010/MainThread) mssqlcli.mssqlcliclient ERROR - System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 25 - Connection string is not valid)
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.<>c__DisplayClass40_0.<TryGetConnection>b__1(Task`1 _)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.SqlTools.ServiceLayer.Connection.ReliableConnection.ReliableSqlConnection.<>c__DisplayClass28_0.<<OpenAsync>b__0>d.MoveNext() in D:\a\1\s\src\Microsoft.SqlTools.ManagedBatchParser\ReliableConnection\ReliableSqlConnection.cs:line 303
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.TryOpenConnection(ConnectionInfo connectionInfo, ConnectParams connectionParams) in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\Connection\ConnectionService.cs:line 521
ClientConnectionId:00000000-0000-0000-0000-000000000000
2023-05-23 07:11:06,160 (3010/MainThread) mssqlcli.jsonrpc.jsonrpcclient INFO - Shutting down Json rpc client.
2023-05-23 07:11:06,160 (3010/MainThread) mssqlcli.sqltoolsclient INFO - Shutting down Sql Tools Client Process Id: 3012
2023-05-23 07:11:06,261 (3010/MainThread) mssqlcli.mssqlcliclient INFO - Shutdown MssqlCliClient
2023-05-23 07:11:06,262 (3010/MainThread) mssqlcli.jsonrpc.jsonrpcclient INFO - Shutting down Json rpc client.
2023-05-23 07:11:06,262 (3010/MainThread) mssqlcli.sqltoolsclient INFO - Shutting down Sql Tools Client Process Id: 3012
2023-05-23 07:11:26,145 (3040/MainThread) mssqlcli INFO - Initializing mssqlcli logging.
2023-05-23 07:11:26,146 (3040/MainThread) mssqlcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-05-23 07:11:26,148 (3040/MainThread) mssqlcli.sqltoolsclient INFO - SqlToolsService process id: 3042
2023-05-23 07:11:26,149 (3040/MainThread) mssqlcli.sqltoolsclient INFO - Sql Tools Client Initialized
2023-05-23 07:11:26,149 (3040/MainThread) mssqlcli.mssqlcliclient INFO - Initialized MssqlCliClient with owner Uri mssql-cli-urn:uuid:e52e2914-0e6a-42b6-8c93-b4f40890e437
2023-05-23 07:11:26,149 (3040/MainThread) mssqlcli.sqltoolsclient INFO - SqlToolsClient connection request Id 111837094191002685463562613902301700548 and owner Uri mssql-cli-urn:uuid:e52e2914-0e6a-42b6-8c93-b4f40890e437
2023-05-23 07:11:26,568 (3040/Json_Rpc_Response_Thread) mssqlcli.jsonrpc.jsonrpcclient INFO - {'jsonrpc': '2.0', 'id': '111837094191002685463562613902301700548', 'result': True}
2023-05-23 07:11:41,189 (3040/Json_Rpc_Response_Thread) mssqlcli.jsonrpc.jsonrpcclient INFO - {'jsonrpc': '2.0', 'method': 'connection/complete', 'params': {'ownerUri': 'mssql-cli-urn:uuid:e52e2914-0e6a-42b6-8c93-b4f40890e437', 'connectionId': None, 'messages': 'System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 25 - Connection string is not valid)\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken)\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\n   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)\n   at System.Data.ProviderBase.DbConnectionFactory.<>c__DisplayClass40_0.<TryGetConnection>b__1(Task`1 _)\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)\n--- End of stack trace from previous location where exception was thrown ---\n   at Microsoft.SqlTools.ServiceLayer.Connection.ReliableConnection.ReliableSqlConnection.<>c__DisplayClass28_0.<<OpenAsync>b__0>d.MoveNext() in D:\\a\\1\\s\\src\\Microsoft.SqlTools.ManagedBatchParser\\ReliableConnection\\ReliableSqlConnection.cs:line 303\n--- End of stack trace from previous location where exception was thrown ---\n   at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.TryOpenConnection(ConnectionInfo connectionInfo, ConnectParams connectionParams) in D:\\a\\1\\s\\src\\Microsoft.SqlTools.ServiceLayer\\Connection\\ConnectionService.cs:line 521\nClientConnectionId:00000000-0000-0000-0000-000000000000', 'errorMessage': 'A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 25 - Connection string is not valid)', 'errorNumber': 0, 'serverInfo': None, 'connectionSummary': None, 'type': 'Default'}}
2023-05-23 07:11:41,240 (3040/MainThread) mssqlcli.mssqlcliclient ERROR - System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 25 - Connection string is not valid)
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.<>c__DisplayClass40_0.<TryGetConnection>b__1(Task`1 _)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.SqlTools.ServiceLayer.Connection.ReliableConnection.ReliableSqlConnection.<>c__DisplayClass28_0.<<OpenAsync>b__0>d.MoveNext() in D:\a\1\s\src\Microsoft.SqlTools.ManagedBatchParser\ReliableConnection\ReliableSqlConnection.cs:line 303
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.TryOpenConnection(ConnectionInfo connectionInfo, ConnectParams connectionParams) in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\Connection\ConnectionService.cs:line 521
ClientConnectionId:00000000-0000-0000-0000-000000000000
2023-05-23 07:11:41,240 (3040/MainThread) mssqlcli.jsonrpc.jsonrpcclient INFO - Shutting down Json rpc client.
2023-05-23 07:11:41,240 (3040/MainThread) mssqlcli.sqltoolsclient INFO - Shutting down Sql Tools Client Process Id: 3042
2023-05-23 07:11:41,341 (3040/MainThread) mssqlcli.mssqlcliclient INFO - Shutdown MssqlCliClient
2023-05-23 07:11:41,342 (3040/MainThread) mssqlcli.jsonrpc.jsonrpcclient INFO - Shutting down Json rpc client.
2023-05-23 07:11:41,342 (3040/MainThread) mssqlcli.sqltoolsclient INFO - Shutting down Sql Tools Client Process Id: 3042
2023-05-23 07:12:01,526 (3071/MainThread) mssqlcli INFO - Initializing mssqlcli logging.
2023-05-23 07:12:01,527 (3071/MainThread) mssqlcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-05-23 07:12:01,529 (3071/MainThread) mssqlcli.sqltoolsclient INFO - SqlToolsService process id: 3073
2023-05-23 07:12:01,530 (3071/MainThread) mssqlcli.sqltoolsclient INFO - Sql Tools Client Initialized
2023-05-23 07:12:01,530 (3071/MainThread) mssqlcli.mssqlcliclient INFO - Initialized MssqlCliClient with owner Uri mssql-cli-urn:uuid:00ac8f2d-08bb-4117-93ca-0b63021a8eb6
2023-05-23 07:12:01,531 (3071/MainThread) mssqlcli.sqltoolsclient INFO - SqlToolsClient connection request Id 34824460368426013069734357802316936382 and owner Uri mssql-cli-urn:uuid:00ac8f2d-08bb-4117-93ca-0b63021a8eb6
2023-05-23 07:12:01,963 (3071/Json_Rpc_Response_Thread) mssqlcli.jsonrpc.jsonrpcclient INFO - {'jsonrpc': '2.0', 'id': '34824460368426013069734357802316936382', 'result': True}
2023-05-23 07:12:16,602 (3071/Json_Rpc_Response_Thread) mssqlcli.jsonrpc.jsonrpcclient INFO - {'jsonrpc': '2.0', 'method': 'connection/complete', 'params': {'ownerUri': 'mssql-cli-urn:uuid:00ac8f2d-08bb-4117-93ca-0b63021a8eb6', 'connectionId': None, 'messages': 'System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 35 - An internal exception was caught) ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000005, 6): No such device or address\n   at System.Net.Dns.InternalGetHostByName(String hostName)\n   at System.Net.Dns.GetHostAddresses(String hostNameOrAddress)\n   at System.Data.SqlClient.SNI.SNITCPHandle.Connect(String serverName, Int32 port, TimeSpan timeout)\n   at System.Data.SqlClient.SNI.SNITCPHandle..ctor(String serverName, Int32 port, Int64 timerExpire, Object callbackObject, Boolean parallel)\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken)\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\n   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)\n   at System.Data.ProviderBase.DbConnectionFactory.<>c__DisplayClass40_0.<TryGetConnection>b__1(Task`1 _)\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)\n--- End of stack trace from previous location where exception was thrown ---\n   at Microsoft.SqlTools.ServiceLayer.Connection.ReliableConnection.ReliableSqlConnection.<>c__DisplayClass28_0.<<OpenAsync>b__0>d.MoveNext() in D:\\a\\1\\s\\src\\Microsoft.SqlTools.ManagedBatchParser\\ReliableConnection\\ReliableSqlConnection.cs:line 303\n--- End of stack trace from previous location where exception was thrown ---\n   at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.TryOpenConnection(ConnectionInfo connectionInfo, ConnectParams connectionParams) in D:\\a\\1\\s\\src\\Microsoft.SqlTools.ServiceLayer\\Connection\\ConnectionService.cs:line 521\nClientConnectionId:00000000-0000-0000-0000-000000000000', 'errorMessage': 'A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 35 - An internal exception was caught)', 'errorNumber': 0, 'serverInfo': None, 'connectionSummary': None, 'type': 'Default'}}
2023-05-23 07:12:16,606 (3071/MainThread) mssqlcli.mssqlcliclient ERROR - System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 35 - An internal exception was caught) ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000005, 6): No such device or address
   at System.Net.Dns.InternalGetHostByName(String hostName)
   at System.Net.Dns.GetHostAddresses(String hostNameOrAddress)
   at System.Data.SqlClient.SNI.SNITCPHandle.Connect(String serverName, Int32 port, TimeSpan timeout)
   at System.Data.SqlClient.SNI.SNITCPHandle..ctor(String serverName, Int32 port, Int64 timerExpire, Object callbackObject, Boolean parallel)
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.<>c__DisplayClass40_0.<TryGetConnection>b__1(Task`1 _)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.SqlTools.ServiceLayer.Connection.ReliableConnection.ReliableSqlConnection.<>c__DisplayClass28_0.<<OpenAsync>b__0>d.MoveNext() in D:\a\1\s\src\Microsoft.SqlTools.ManagedBatchParser\ReliableConnection\ReliableSqlConnection.cs:line 303
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.TryOpenConnection(ConnectionInfo connectionInfo, ConnectParams connectionParams) in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\Connection\ConnectionService.cs:line 521
ClientConnectionId:00000000-0000-0000-0000-000000000000
2023-05-23 07:12:16,606 (3071/MainThread) mssqlcli.jsonrpc.jsonrpcclient INFO - Shutting down Json rpc client.
2023-05-23 07:12:16,607 (3071/MainThread) mssqlcli.sqltoolsclient INFO - Shutting down Sql Tools Client Process Id: 3073
2023-05-23 07:12:16,707 (3071/MainThread) mssqlcli.mssqlcliclient INFO - Shutdown MssqlCliClient
2023-05-23 07:12:16,709 (3071/MainThread) mssqlcli.jsonrpc.jsonrpcclient INFO - Shutting down Json rpc client.
2023-05-23 07:12:16,709 (3071/MainThread) mssqlcli.sqltoolsclient INFO - Shutting down Sql Tools Client Process Id: 3073
2023-05-23 07:13:03,555 (3105/MainThread) mssqlcli INFO - Initializing mssqlcli logging.
2023-05-23 07:13:03,557 (3105/MainThread) mssqlcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-05-23 07:13:03,559 (3105/MainThread) mssqlcli.sqltoolsclient INFO - SqlToolsService process id: 3107
2023-05-23 07:13:03,559 (3105/MainThread) mssqlcli.sqltoolsclient INFO - Sql Tools Client Initialized
2023-05-23 07:13:03,560 (3105/MainThread) mssqlcli.mssqlcliclient INFO - Initialized MssqlCliClient with owner Uri mssql-cli-urn:uuid:fcdcd2e2-1731-4938-8acc-bf5facc4b316
2023-05-23 07:13:03,560 (3105/MainThread) mssqlcli.sqltoolsclient INFO - SqlToolsClient connection request Id 96018238739384927203516399644737730388 and owner Uri mssql-cli-urn:uuid:fcdcd2e2-1731-4938-8acc-bf5facc4b316
2023-05-23 07:13:03,995 (3105/Json_Rpc_Response_Thread) mssqlcli.jsonrpc.jsonrpcclient INFO - {'jsonrpc': '2.0', 'id': '96018238739384927203516399644737730388', 'result': True}
2023-05-23 07:13:18,922 (3105/Json_Rpc_Response_Thread) mssqlcli.jsonrpc.jsonrpcclient INFO - {'jsonrpc': '2.0', 'method': 'connection/complete', 'params': {'ownerUri': 'mssql-cli-urn:uuid:fcdcd2e2-1731-4938-8acc-bf5facc4b316', 'connectionId': None, 'messages': 'System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 40 - Could not open a connection to SQL Server)\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken)\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\n   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)\n   at System.Data.ProviderBase.DbConnectionFactory.<>c__DisplayClass40_0.<TryGetConnection>b__1(Task`1 _)\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)\n--- End of stack trace from previous location where exception was thrown ---\n   at Microsoft.SqlTools.ServiceLayer.Connection.ReliableConnection.ReliableSqlConnection.<>c__DisplayClass28_0.<<OpenAsync>b__0>d.MoveNext() in D:\\a\\1\\s\\src\\Microsoft.SqlTools.ManagedBatchParser\\ReliableConnection\\ReliableSqlConnection.cs:line 303\n--- End of stack trace from previous location where exception was thrown ---\n   at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.TryOpenConnection(ConnectionInfo connectionInfo, ConnectParams connectionParams) in D:\\a\\1\\s\\src\\Microsoft.SqlTools.ServiceLayer\\Connection\\ConnectionService.cs:line 521\nClientConnectionId:00000000-0000-0000-0000-000000000000', 'errorMessage': 'A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 40 - Could not open a connection to SQL Server)', 'errorNumber': 0, 'serverInfo': None, 'connectionSummary': None, 'type': 'Default'}}
2023-05-23 07:13:18,947 (3105/MainThread) mssqlcli.mssqlcliclient ERROR - System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 40 - Could not open a connection to SQL Server)
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.<>c__DisplayClass40_0.<TryGetConnection>b__1(Task`1 _)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.SqlTools.ServiceLayer.Connection.ReliableConnection.ReliableSqlConnection.<>c__DisplayClass28_0.<<OpenAsync>b__0>d.MoveNext() in D:\a\1\s\src\Microsoft.SqlTools.ManagedBatchParser\ReliableConnection\ReliableSqlConnection.cs:line 303
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.TryOpenConnection(ConnectionInfo connectionInfo, ConnectParams connectionParams) in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\Connection\ConnectionService.cs:line 521
ClientConnectionId:00000000-0000-0000-0000-000000000000
2023-05-23 07:13:18,947 (3105/MainThread) mssqlcli.jsonrpc.jsonrpcclient INFO - Shutting down Json rpc client.
2023-05-23 07:13:18,947 (3105/MainThread) mssqlcli.sqltoolsclient INFO - Shutting down Sql Tools Client Process Id: 3107
2023-05-23 07:13:19,048 (3105/MainThread) mssqlcli.mssqlcliclient INFO - Shutdown MssqlCliClient
2023-05-23 07:13:19,050 (3105/MainThread) mssqlcli.jsonrpc.jsonrpcclient INFO - Shutting down Json rpc client.
2023-05-23 07:13:19,050 (3105/MainThread) mssqlcli.sqltoolsclient INFO - Shutting down Sql Tools Client Process Id: 3107
2023-05-23 07:13:33,812 (3137/MainThread) mssqlcli INFO - Initializing mssqlcli logging.
2023-05-23 07:13:33,813 (3137/MainThread) mssqlcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-05-23 07:13:33,815 (3137/MainThread) mssqlcli.sqltoolsclient INFO - SqlToolsService process id: 3139
2023-05-23 07:13:33,816 (3137/MainThread) mssqlcli.sqltoolsclient INFO - Sql Tools Client Initialized
2023-05-23 07:13:33,816 (3137/MainThread) mssqlcli.mssqlcliclient INFO - Initialized MssqlCliClient with owner Uri mssql-cli-urn:uuid:51ae64d2-54bb-409b-a396-130b5761276f
2023-05-23 07:13:33,816 (3137/MainThread) mssqlcli.sqltoolsclient INFO - SqlToolsClient connection request Id 210814715710945477537503440576823126414 and owner Uri mssql-cli-urn:uuid:51ae64d2-54bb-409b-a396-130b5761276f
2023-05-23 07:13:34,251 (3137/Json_Rpc_Response_Thread) mssqlcli.jsonrpc.jsonrpcclient INFO - {'jsonrpc': '2.0', 'id': '210814715710945477537503440576823126414', 'result': True}
2023-05-23 07:13:34,779 (3137/Json_Rpc_Response_Thread) mssqlcli.jsonrpc.jsonrpcclient INFO - {'jsonrpc': '2.0', 'method': 'connection/complete', 'params': {'ownerUri': 'mssql-cli-urn:uuid:51ae64d2-54bb-409b-a396-130b5761276f', 'connectionId': None, 'messages': "System.Data.SqlClient.SqlException (0x80131904): Cannot authenticate using Kerberos. Ensure Kerberos has been initialized on the client with 'kinit' and a Service Principal Name has been registered for the SQL Server to allow Kerberos authentication.\nErrorCode=InternalError, Exception=Interop+NetSecurityNative+GssApiException: GSSAPI operation failed with error - An invalid status code was supplied (SPNEGO cannot find mechanisms to negotiate).\n   at System.Net.Security.NegotiateStreamPal.GssInitSecurityContext(SafeGssContextHandle& context, SafeGssCredHandle credential, Boolean isNtlm, SafeGssNameHandle targetName, GssFlags inFlags, Byte[] buffer, Byte[]& outputBuffer, UInt32& outFlags, Int32& isNtlmUsed)\n   at System.Net.Security.NegotiateStreamPal.EstablishSecurityContext(SafeFreeNegoCredentials credential, SafeDeleteContext& context, String targetName, ContextFlagsPal inFlags, SecurityBuffer inputBuffer, SecurityBuffer outputBuffer, ContextFlagsPal& outFlags)\n   at System.Data.SqlClient.SNI.SNIProxy.GenSspiClientContext(SspiClientContextStatus sspiClientContextStatus, Byte[] receivedBuff, Byte[]& sendBuff, Byte[] serverName)\n   at System.Data.SqlClient.SNI.TdsParserStateObjectManaged.GenerateSspiClientContext(Byte[] receivedBuff, UInt32 receivedLength, Byte[]& sendBuff, UInt32& sendLength, Byte[] _sniSpnBuffer)\n   at System.Data.SqlClient.TdsParser.SNISSPIData(Byte[] receivedBuff, UInt32 receivedLength, Byte[]& sendBuff, UInt32& sendLength)\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken)\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\n   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)\n   at System.Data.ProviderBase.DbConnectionFactory.<>c__DisplayClass40_0.<TryGetConnection>b__1(Task`1 _)\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)\n--- End of stack trace from previous location where exception was thrown ---\n   at Microsoft.SqlTools.ServiceLayer.Connection.ReliableConnection.ReliableSqlConnection.<>c__DisplayClass28_0.<<OpenAsync>b__0>d.MoveNext() in D:\\a\\1\\s\\src\\Microsoft.SqlTools.ManagedBatchParser\\ReliableConnection\\ReliableSqlConnection.cs:line 303\n--- End of stack trace from previous location where exception was thrown ---\n   at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.TryOpenConnection(ConnectionInfo connectionInfo, ConnectParams connectionParams) in D:\\a\\1\\s\\src\\Microsoft.SqlTools.ServiceLayer\\Connection\\ConnectionService.cs:line 521\nClientConnectionId:9b2a3bf6-e4bf-44d1-ba2d-c64e06e48977", 'errorMessage': "Cannot authenticate using Kerberos. Ensure Kerberos has been initialized on the client with 'kinit' and a Service Principal Name has been registered for the SQL Server to allow Kerberos authentication.\nErrorCode=InternalError, Exception=Interop+NetSecurityNative+GssApiException: GSSAPI operation failed with error - An invalid status code was supplied (SPNEGO cannot find mechanisms to negotiate).\n   at System.Net.Security.NegotiateStreamPal.GssInitSecurityContext(SafeGssContextHandle& context, SafeGssCredHandle credential, Boolean isNtlm, SafeGssNameHandle targetName, GssFlags inFlags, Byte[] buffer, Byte[]& outputBuffer, UInt32& outFlags, Int32& isNtlmUsed)\n   at System.Net.Security.NegotiateStreamPal.EstablishSecurityContext(SafeFreeNegoCredentials credential, SafeDeleteContext& context, String targetName, ContextFlagsPal inFlags, SecurityBuffer inputBuffer, SecurityBuffer outputBuffer, ContextFlagsPal& outFlags)\n   at System.Data.SqlClient.SNI.SNIProxy.GenSspiClientContext(SspiClientContextStatus sspiClientContextStatus, Byte[] receivedBuff, Byte[]& sendBuff, Byte[] serverName)\n   at System.Data.SqlClient.SNI.TdsParserStateObjectManaged.GenerateSspiClientContext(Byte[] receivedBuff, UInt32 receivedLength, Byte[]& sendBuff, UInt32& sendLength, Byte[] _sniSpnBuffer)\n   at System.Data.SqlClient.TdsParser.SNISSPIData(Byte[] receivedBuff, UInt32 receivedLength, Byte[]& sendBuff, UInt32& sendLength)", 'errorNumber': 0, 'serverInfo': None, 'connectionSummary': None, 'type': 'Default'}}
2023-05-23 07:13:34,821 (3137/MainThread) mssqlcli.mssqlcliclient ERROR - System.Data.SqlClient.SqlException (0x80131904): Cannot authenticate using Kerberos. Ensure Kerberos has been initialized on the client with 'kinit' and a Service Principal Name has been registered for the SQL Server to allow Kerberos authentication.
ErrorCode=InternalError, Exception=Interop+NetSecurityNative+GssApiException: GSSAPI operation failed with error - An invalid status code was supplied (SPNEGO cannot find mechanisms to negotiate).
   at System.Net.Security.NegotiateStreamPal.GssInitSecurityContext(SafeGssContextHandle& context, SafeGssCredHandle credential, Boolean isNtlm, SafeGssNameHandle targetName, GssFlags inFlags, Byte[] buffer, Byte[]& outputBuffer, UInt32& outFlags, Int32& isNtlmUsed)
   at System.Net.Security.NegotiateStreamPal.EstablishSecurityContext(SafeFreeNegoCredentials credential, SafeDeleteContext& context, String targetName, ContextFlagsPal inFlags, SecurityBuffer inputBuffer, SecurityBuffer outputBuffer, ContextFlagsPal& outFlags)
   at System.Data.SqlClient.SNI.SNIProxy.GenSspiClientContext(SspiClientContextStatus sspiClientContextStatus, Byte[] receivedBuff, Byte[]& sendBuff, Byte[] serverName)
   at System.Data.SqlClient.SNI.TdsParserStateObjectManaged.GenerateSspiClientContext(Byte[] receivedBuff, UInt32 receivedLength, Byte[]& sendBuff, UInt32& sendLength, Byte[] _sniSpnBuffer)
   at System.Data.SqlClient.TdsParser.SNISSPIData(Byte[] receivedBuff, UInt32 receivedLength, Byte[]& sendBuff, UInt32& sendLength)
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.<>c__DisplayClass40_0.<TryGetConnection>b__1(Task`1 _)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.SqlTools.ServiceLayer.Connection.ReliableConnection.ReliableSqlConnection.<>c__DisplayClass28_0.<<OpenAsync>b__0>d.MoveNext() in D:\a\1\s\src\Microsoft.SqlTools.ManagedBatchParser\ReliableConnection\ReliableSqlConnection.cs:line 303
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.TryOpenConnection(ConnectionInfo connectionInfo, ConnectParams connectionParams) in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\Connection\ConnectionService.cs:line 521
ClientConnectionId:9b2a3bf6-e4bf-44d1-ba2d-c64e06e48977
2023-05-23 07:13:34,821 (3137/MainThread) mssqlcli.jsonrpc.jsonrpcclient INFO - Shutting down Json rpc client.
2023-05-23 07:13:34,821 (3137/MainThread) mssqlcli.sqltoolsclient INFO - Shutting down Sql Tools Client Process Id: 3139
2023-05-23 07:13:34,922 (3137/MainThread) mssqlcli.mssqlcliclient INFO - Shutdown MssqlCliClient
2023-05-23 07:13:34,924 (3137/MainThread) mssqlcli.jsonrpc.jsonrpcclient INFO - Shutting down Json rpc client.
2023-05-23 07:13:34,924 (3137/MainThread) mssqlcli.sqltoolsclient INFO - Shutting down Sql Tools Client Process Id: 3139
2023-05-23 07:13:39,897 (3168/MainThread) mssqlcli INFO - Initializing mssqlcli logging.
2023-05-23 07:13:39,900 (3168/MainThread) mssqlcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-05-23 07:13:39,905 (3168/MainThread) mssqlcli.sqltoolsclient INFO - SqlToolsService process id: 3170
2023-05-23 07:13:39,906 (3168/MainThread) mssqlcli.sqltoolsclient INFO - Sql Tools Client Initialized
2023-05-23 07:13:39,907 (3168/MainThread) mssqlcli.mssqlcliclient INFO - Initialized MssqlCliClient with owner Uri mssql-cli-urn:uuid:8762a6a7-c25c-4682-bf24-cc68bd40db68
2023-05-23 07:13:39,907 (3168/MainThread) mssqlcli.sqltoolsclient INFO - SqlToolsClient connection request Id 33397208415169779501622937560886657691 and owner Uri mssql-cli-urn:uuid:8762a6a7-c25c-4682-bf24-cc68bd40db68
2023-05-23 07:13:41,020 (3168/Json_Rpc_Response_Thread) mssqlcli.jsonrpc.jsonrpcclient INFO - {'jsonrpc': '2.0', 'id': '33397208415169779501622937560886657691', 'result': True}
2023-05-23 07:13:41,917 (3168/Json_Rpc_Response_Thread) mssqlcli.jsonrpc.jsonrpcclient INFO - {'jsonrpc': '2.0', 'method': 'connection/complete', 'params': {'ownerUri': 'mssql-cli-urn:uuid:8762a6a7-c25c-4682-bf24-cc68bd40db68', 'connectionId': None, 'messages': "System.Data.SqlClient.SqlException (0x80131904): Cannot authenticate using Kerberos. Ensure Kerberos has been initialized on the client with 'kinit' and a Service Principal Name has been registered for the SQL Server to allow Kerberos authentication.\nErrorCode=InternalError, Exception=Interop+NetSecurityNative+GssApiException: GSSAPI operation failed with error - An invalid status code was supplied (SPNEGO cannot find mechanisms to negotiate).\n   at System.Net.Security.NegotiateStreamPal.GssInitSecurityContext(SafeGssContextHandle& context, SafeGssCredHandle credential, Boolean isNtlm, SafeGssNameHandle targetName, GssFlags inFlags, Byte[] buffer, Byte[]& outputBuffer, UInt32& outFlags, Int32& isNtlmUsed)\n   at System.Net.Security.NegotiateStreamPal.EstablishSecurityContext(SafeFreeNegoCredentials credential, SafeDeleteContext& context, String targetName, ContextFlagsPal inFlags, SecurityBuffer inputBuffer, SecurityBuffer outputBuffer, ContextFlagsPal& outFlags)\n   at System.Data.SqlClient.SNI.SNIProxy.GenSspiClientContext(SspiClientContextStatus sspiClientContextStatus, Byte[] receivedBuff, Byte[]& sendBuff, Byte[] serverName)\n   at System.Data.SqlClient.SNI.TdsParserStateObjectManaged.GenerateSspiClientContext(Byte[] receivedBuff, UInt32 receivedLength, Byte[]& sendBuff, UInt32& sendLength, Byte[] _sniSpnBuffer)\n   at System.Data.SqlClient.TdsParser.SNISSPIData(Byte[] receivedBuff, UInt32 receivedLength, Byte[]& sendBuff, UInt32& sendLength)\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken)\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\n   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)\n   at System.Data.ProviderBase.DbConnectionFactory.<>c__DisplayClass40_0.<TryGetConnection>b__1(Task`1 _)\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)\n--- End of stack trace from previous location where exception was thrown ---\n   at Microsoft.SqlTools.ServiceLayer.Connection.ReliableConnection.ReliableSqlConnection.<>c__DisplayClass28_0.<<OpenAsync>b__0>d.MoveNext() in D:\\a\\1\\s\\src\\Microsoft.SqlTools.ManagedBatchParser\\ReliableConnection\\ReliableSqlConnection.cs:line 303\n--- End of stack trace from previous location where exception was thrown ---\n   at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.TryOpenConnection(ConnectionInfo connectionInfo, ConnectParams connectionParams) in D:\\a\\1\\s\\src\\Microsoft.SqlTools.ServiceLayer\\Connection\\ConnectionService.cs:line 521\nClientConnectionId:d078acea-1f14-4a10-9629-d93521281fad", 'errorMessage': "Cannot authenticate using Kerberos. Ensure Kerberos has been initialized on the client with 'kinit' and a Service Principal Name has been registered for the SQL Server to allow Kerberos authentication.\nErrorCode=InternalError, Exception=Interop+NetSecurityNative+GssApiException: GSSAPI operation failed with error - An invalid status code was supplied (SPNEGO cannot find mechanisms to negotiate).\n   at System.Net.Security.NegotiateStreamPal.GssInitSecurityContext(SafeGssContextHandle& context, SafeGssCredHandle credential, Boolean isNtlm, SafeGssNameHandle targetName, GssFlags inFlags, Byte[] buffer, Byte[]& outputBuffer, UInt32& outFlags, Int32& isNtlmUsed)\n   at System.Net.Security.NegotiateStreamPal.EstablishSecurityContext(SafeFreeNegoCredentials credential, SafeDeleteContext& context, String targetName, ContextFlagsPal inFlags, SecurityBuffer inputBuffer, SecurityBuffer outputBuffer, ContextFlagsPal& outFlags)\n   at System.Data.SqlClient.SNI.SNIProxy.GenSspiClientContext(SspiClientContextStatus sspiClientContextStatus, Byte[] receivedBuff, Byte[]& sendBuff, Byte[] serverName)\n   at System.Data.SqlClient.SNI.TdsParserStateObjectManaged.GenerateSspiClientContext(Byte[] receivedBuff, UInt32 receivedLength, Byte[]& sendBuff, UInt32& sendLength, Byte[] _sniSpnBuffer)\n   at System.Data.SqlClient.TdsParser.SNISSPIData(Byte[] receivedBuff, UInt32 receivedLength, Byte[]& sendBuff, UInt32& sendLength)", 'errorNumber': 0, 'serverInfo': None, 'connectionSummary': None, 'type': 'Default'}}
2023-05-23 07:13:41,966 (3168/MainThread) mssqlcli.mssqlcliclient ERROR - System.Data.SqlClient.SqlException (0x80131904): Cannot authenticate using Kerberos. Ensure Kerberos has been initialized on the client with 'kinit' and a Service Principal Name has been registered for the SQL Server to allow Kerberos authentication.
ErrorCode=InternalError, Exception=Interop+NetSecurityNative+GssApiException: GSSAPI operation failed with error - An invalid status code was supplied (SPNEGO cannot find mechanisms to negotiate).
   at System.Net.Security.NegotiateStreamPal.GssInitSecurityContext(SafeGssContextHandle& context, SafeGssCredHandle credential, Boolean isNtlm, SafeGssNameHandle targetName, GssFlags inFlags, Byte[] buffer, Byte[]& outputBuffer, UInt32& outFlags, Int32& isNtlmUsed)
   at System.Net.Security.NegotiateStreamPal.EstablishSecurityContext(SafeFreeNegoCredentials credential, SafeDeleteContext& context, String targetName, ContextFlagsPal inFlags, SecurityBuffer inputBuffer, SecurityBuffer outputBuffer, ContextFlagsPal& outFlags)
   at System.Data.SqlClient.SNI.SNIProxy.GenSspiClientContext(SspiClientContextStatus sspiClientContextStatus, Byte[] receivedBuff, Byte[]& sendBuff, Byte[] serverName)
   at System.Data.SqlClient.SNI.TdsParserStateObjectManaged.GenerateSspiClientContext(Byte[] receivedBuff, UInt32 receivedLength, Byte[]& sendBuff, UInt32& sendLength, Byte[] _sniSpnBuffer)
   at System.Data.SqlClient.TdsParser.SNISSPIData(Byte[] receivedBuff, UInt32 receivedLength, Byte[]& sendBuff, UInt32& sendLength)
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.<>c__DisplayClass40_0.<TryGetConnection>b__1(Task`1 _)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.SqlTools.ServiceLayer.Connection.ReliableConnection.ReliableSqlConnection.<>c__DisplayClass28_0.<<OpenAsync>b__0>d.MoveNext() in D:\a\1\s\src\Microsoft.SqlTools.ManagedBatchParser\ReliableConnection\ReliableSqlConnection.cs:line 303
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.TryOpenConnection(ConnectionInfo connectionInfo, ConnectParams connectionParams) in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\Connection\ConnectionService.cs:line 521
ClientConnectionId:d078acea-1f14-4a10-9629-d93521281fad
2023-05-23 07:13:41,967 (3168/MainThread) mssqlcli.jsonrpc.jsonrpcclient INFO - Shutting down Json rpc client.
2023-05-23 07:13:41,967 (3168/MainThread) mssqlcli.sqltoolsclient INFO - Shutting down Sql Tools Client Process Id: 3170
2023-05-23 07:13:42,068 (3168/MainThread) mssqlcli.mssqlcliclient INFO - Shutdown MssqlCliClient
2023-05-23 07:13:42,071 (3168/MainThread) mssqlcli.jsonrpc.jsonrpcclient INFO - Shutting down Json rpc client.
2023-05-23 07:13:42,072 (3168/MainThread) mssqlcli.sqltoolsclient INFO - Shutting down Sql Tools Client Process Id: 3170
2023-05-23 07:13:45,438 (3195/MainThread) mssqlcli INFO - Initializing mssqlcli logging.
2023-05-23 07:13:45,441 (3195/MainThread) mssqlcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-05-23 07:13:45,444 (3195/MainThread) mssqlcli.sqltoolsclient INFO - SqlToolsService process id: 3197
2023-05-23 07:13:45,445 (3195/MainThread) mssqlcli.sqltoolsclient INFO - Sql Tools Client Initialized
2023-05-23 07:13:45,446 (3195/MainThread) mssqlcli.mssqlcliclient INFO - Initialized MssqlCliClient with owner Uri mssql-cli-urn:uuid:4fa8ed2b-f216-4912-8af3-2945f91ed154
2023-05-23 07:13:45,446 (3195/MainThread) mssqlcli.sqltoolsclient INFO - SqlToolsClient connection request Id 109314275317118329961332788344866089323 and owner Uri mssql-cli-urn:uuid:4fa8ed2b-f216-4912-8af3-2945f91ed154
2023-05-23 07:13:46,335 (3195/Json_Rpc_Response_Thread) mssqlcli.jsonrpc.jsonrpcclient INFO - {'jsonrpc': '2.0', 'id': '109314275317118329961332788344866089323', 'result': True}
2023-05-23 07:14:01,017 (3195/Json_Rpc_Response_Thread) mssqlcli.jsonrpc.jsonrpcclient INFO - {'jsonrpc': '2.0', 'method': 'connection/complete', 'params': {'ownerUri': 'mssql-cli-urn:uuid:4fa8ed2b-f216-4912-8af3-2945f91ed154', 'connectionId': None, 'messages': 'System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 35 - An internal exception was caught) ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000005, 6): No such device or address\n   at System.Net.Dns.InternalGetHostByName(String hostName)\n   at System.Net.Dns.GetHostAddresses(String hostNameOrAddress)\n   at System.Data.SqlClient.SNI.SNITCPHandle.Connect(String serverName, Int32 port, TimeSpan timeout)\n   at System.Data.SqlClient.SNI.SNITCPHandle..ctor(String serverName, Int32 port, Int64 timerExpire, Object callbackObject, Boolean parallel)\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken)\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\n   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)\n   at System.Data.ProviderBase.DbConnectionFactory.<>c__DisplayClass40_0.<TryGetConnection>b__1(Task`1 _)\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)\n--- End of stack trace from previous location where exception was thrown ---\n   at Microsoft.SqlTools.ServiceLayer.Connection.ReliableConnection.ReliableSqlConnection.<>c__DisplayClass28_0.<<OpenAsync>b__0>d.MoveNext() in D:\\a\\1\\s\\src\\Microsoft.SqlTools.ManagedBatchParser\\ReliableConnection\\ReliableSqlConnection.cs:line 303\n--- End of stack trace from previous location where exception was thrown ---\n   at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.TryOpenConnection(ConnectionInfo connectionInfo, ConnectParams connectionParams) in D:\\a\\1\\s\\src\\Microsoft.SqlTools.ServiceLayer\\Connection\\ConnectionService.cs:line 521\nClientConnectionId:00000000-0000-0000-0000-000000000000', 'errorMessage': 'A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 35 - An internal exception was caught)', 'errorNumber': 0, 'serverInfo': None, 'connectionSummary': None, 'type': 'Default'}}
2023-05-23 07:14:01,033 (3195/MainThread) mssqlcli.mssqlcliclient ERROR - System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 35 - An internal exception was caught) ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000005, 6): No such device or address
   at System.Net.Dns.InternalGetHostByName(String hostName)
   at System.Net.Dns.GetHostAddresses(String hostNameOrAddress)
   at System.Data.SqlClient.SNI.SNITCPHandle.Connect(String serverName, Int32 port, TimeSpan timeout)
   at System.Data.SqlClient.SNI.SNITCPHandle..ctor(String serverName, Int32 port, Int64 timerExpire, Object callbackObject, Boolean parallel)
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.<>c__DisplayClass40_0.<TryGetConnection>b__1(Task`1 _)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.SqlTools.ServiceLayer.Connection.ReliableConnection.ReliableSqlConnection.<>c__DisplayClass28_0.<<OpenAsync>b__0>d.MoveNext() in D:\a\1\s\src\Microsoft.SqlTools.ManagedBatchParser\ReliableConnection\ReliableSqlConnection.cs:line 303
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.TryOpenConnection(ConnectionInfo connectionInfo, ConnectParams connectionParams) in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\Connection\ConnectionService.cs:line 521
ClientConnectionId:00000000-0000-0000-0000-000000000000
2023-05-23 07:14:01,033 (3195/MainThread) mssqlcli.jsonrpc.jsonrpcclient INFO - Shutting down Json rpc client.
2023-05-23 07:14:01,033 (3195/MainThread) mssqlcli.sqltoolsclient INFO - Shutting down Sql Tools Client Process Id: 3197
2023-05-23 07:14:01,134 (3195/MainThread) mssqlcli.mssqlcliclient INFO - Shutdown MssqlCliClient
2023-05-23 07:14:01,135 (3195/MainThread) mssqlcli.jsonrpc.jsonrpcclient INFO - Shutting down Json rpc client.
2023-05-23 07:14:01,135 (3195/MainThread) mssqlcli.sqltoolsclient INFO - Shutting down Sql Tools Client Process Id: 3197
